In [1]:
import numpy as np

In [2]:
## Company Data

Hub_North_Sales = np.array([
    [18,20,22,19,21,780,23,20,19,22],
    [12,10,11,13,np.nan,12,14,13,12,11],
    [35,38,36,40,42,39,37,41,38,36],
    [8,7,9,8,6,7,np.nan,8,9,7],
    [25,27,24,26,28,25,23,24,26,27],
    [5,6,4,5,7,6,5,4,6,5]
])

Hub_South_Sales = np.array([
    [15,17,16,18,15,14,16,17,15,16],
    [9,8,np.nan,10,9,7,8,9,10,8],
    [30,32,31,29,33,30,28,31,32,30],
    [6,5,7,6,np.nan,5,6,7,6,5],
    [20,22,21,19,23,20,18,21,22,20],
    [np.nan,3,4,3,5,4,3,4,3,4]
])
# each array: rows = 6 products, columns = 10 days

Cost_Price = np.array([120.0, 250.0, 60.0, 400.0, 150.0, 90.0])
Sell_Price = np.array([180.0, 349.99, 89.99, 560.0, 219.0, 129.99])
# one value per product

Hub_Stock = np.array([
    [15, 8, 40, 5, 20, 6],
    [10, 4, 35, 3, 18, 9]
])
# rows = 2 hubs, columns = 6 products

Return_Log_North = np.array([0, -2, 0, -1, 0, 0, -3, 0, -1, 0])
# units returned by customers each day at North hub (product 0 only, negative = returned)

Promo_Codes = np.array(["WELCOME5","FESTIVE","WELCOME5","FESTIVE","CLEARANCE","WELCOME5","BIGDEAL","FESTIVE","CLEARANCE","WELCOME5"])
Flagged_Promo = np.array(["BIGDEAL","HACKED99"])

New_Hub_Week = np.array([
    [14,16,15,17,14,13,15,16,14,15],
    [7,6,8,7,6,5,7,8,7,6],
    [28,30,29,27,31,28,26,29,30,28],
    [5,4,6,5,4,3,5,6,5,4],
    [18,20,19,17,21,18,16,19,20,18],
    [3,4,2,3,5,4,3,2,4,3]
])
# a 3rd hub's 10-day sheet, same layout as the other two

## Task-1
Print the shape, number of dimensions, and total element count of `hub_north_sales` and `hub_south_sales`. Then print the shape of `cost_price`, `sell_price`, `hub_stock`, and `new_hub_week`.

In [3]:
Shape_1 = Hub_North_Sales.shape
Ndim_1 = np.ndim(Hub_North_Sales)
Total_Elements_1 = np.size(Hub_North_Sales)
print("Shape of Hub North Sales is -",Shape_1)
print("Number of Dimensions of Hub North Sales -",Ndim_1)
print("Total Element count of Hub North Sales -",Total_Elements_1)

print("-"*50)

Shape_2 = Hub_South_Sales.shape
Ndim_2 = np.ndim(Hub_South_Sales)
Total_Elements_2 = np.size(Hub_South_Sales)
print("Shape of Hub South Sales is -",Shape_2)
print("Number of Dimensions of Hub South Sales -",Ndim_2)
print("Total Element count of Hub South Sales -",Total_Elements_2)

print("-"*50)
Shape_3 = Cost_Price.shape
Shape_4 = Sell_Price.shape
Shape_5 = Hub_Stock.shape
Shape_6 = New_Hub_Week.shape
print("Shape of Cost Price -",Shape_3)
print("Shape of Sell Price -",Shape_4)
print("Shape of Hub Stock -",Shape_5)
print("Shape of New Hub Week -",Shape_6)

Shape of Hub North Sales is - (6, 10)
Number of Dimensions of Hub North Sales - 2
Total Element count of Hub North Sales - 60
--------------------------------------------------
Shape of Hub South Sales is - (6, 10)
Number of Dimensions of Hub South Sales - 2
Total Element count of Hub South Sales - 60
--------------------------------------------------
Shape of Cost Price - (6,)
Shape of Sell Price - (6,)
Shape of Hub Stock - (2, 6)
Shape of New Hub Week - (6, 10)


## Task-2
Find the value in `hub_north_sales` that is far larger than everything around it — a clear data-entry mistake — and print its exact row and column position.

In [4]:
Max = np.nanmax(Hub_North_Sales)
print("The Outlier is - ",Max)
Position = np.where(Hub_North_Sales == Max)
print("The Position of Outlier is -",Position)

The Outlier is -  780.0
The Position of Outlier is - (array([0]), array([5]))


## Task-3
Make a copy of `hub_north_sales`. In that copy, replace the value you found in Task 2 with the missing-value marker, so it's treated the same as the other gaps.

In [42]:
Hub_North_Sales_Copy = Hub_North_Sales.copy()
Replace_Outlier = np.where(Hub_North_Sales == Max,np.nan,Hub_North_Sales_Copy)
print("The New Data after replace the Outlier with the missing-value marker in Copy of Hub North Sales :-")
print(Replace_Outlier)

The New Data after replace the Outlier with the missing-value marker in Copy of Hub North Sales :-
[[18. 20. 22. 19. 21. nan 23. 20. 19. 22.]
 [12. 10. 11. 13. nan 12. 14. 13. 12. 11.]
 [35. 38. 36. 40. 42. 39. 37. 41. 38. 36.]
 [ 8.  7.  9.  8.  6.  7. nan  8.  9.  7.]
 [25. 27. 24. 26. 28. 25. 23. 24. 26. 27.]
 [ 5.  6.  4.  5.  7.  6.  5.  4.  6.  5.]]


## Task-4
Count how many values are missing in your corrected `hub_north_sales` copy from Task 3, and how many are missing in `hub_south_sales` — two separate counts.

In [6]:
Missing_Count_Copy = np.sum(np.isnan(Hub_North_Sales_Copy))
print("Total values are missing in  corrected hub_north_sales copy is -",Missing_Count_Copy)
Missing_Count_North = np.sum(np.isnan(Replace_Outlier))
print("Total values are missing in hub_north_sales copy is -",Missing_Count_North)

Total values are missing in  corrected hub_north_sales copy is - 2
Total values are missing in hub_north_sales copy is - 3


## Task-5
Make a cleaned copy of each hub's array. For every product (row) in each hub, fill its missing days with that row's own 10-day average, ignoring the gaps while calculating it. No missing values should remain in either result.

In [41]:
Replacing_With_Mean_North = np.where(np.isnan(Replace_Outlier),np.nanmean(Replace_Outlier,axis = 0),Replace_Outlier)
print("Filling its missing days with that row's own 10-day average of Hub North Sales :-")
print(Replacing_With_Mean_North)

print("-"*50)

Hub_South_Sales_copy = Hub_South_Sales.copy()

Replacing_With_Mean_South = np.where(np.isnan(Hub_South_Sales_copy),np.nanmean(Hub_South_Sales_copy,axis = 0),Hub_South_Sales_copy)
print("Filling its missing days with that row's own 10-day average of Hub South Sales :-")
print(Replacing_With_Mean_South)

Filling its missing days with that row's own 10-day average of Hub North Sales :-
[[18.  20.  22.  19.  21.  17.8 23.  20.  19.  22. ]
 [12.  10.  11.  13.  20.8 12.  14.  13.  12.  11. ]
 [35.  38.  36.  40.  42.  39.  37.  41.  38.  36. ]
 [ 8.   7.   9.   8.   6.   7.  20.4  8.   9.   7. ]
 [25.  27.  24.  26.  28.  25.  23.  24.  26.  27. ]
 [ 5.   6.   4.   5.   7.   6.   5.   4.   6.   5. ]]
--------------------------------------------------
Filling its missing days with that row's own 10-day average of Hub South Sales :-
[[15.  17.  16.  18.  15.  14.  16.  17.  15.  16. ]
 [ 9.   8.  15.8 10.   9.   7.   8.   9.  10.   8. ]
 [30.  32.  31.  29.  33.  30.  28.  31.  32.  30. ]
 [ 6.   5.   7.   6.  17.   5.   6.   7.   6.   5. ]
 [20.  22.  21.  19.  23.  20.  18.  21.  22.  20. ]
 [16.   3.   4.   3.   5.   4.   3.   4.   3.   4. ]]


## Task-6
Using the two cleaned arrays from Task 5, calculate each hub's total units sold for every product (add up all 10 days per row). Print both results.

In [8]:
Total_Units_Sold_North_Per_Product = np.sum(Replacing_With_Mean_North,axis=1)
for i in range(6):
    print(f"Total units sold for {i+1} Product of North is {Total_Units_Sold_North_Per_Product[i]}")

print("-"*50)

Total_Units_Sold_South_Per_Product = np.sum(Replacing_With_Mean_South,axis=1)
for i in range(6):
    print(f"Total units sold for {i+1} Product of South is {Total_Units_Sold_South_Per_Product[i]}")

Total units sold for 1 Product of North is 201.8
Total units sold for 2 Product of North is 128.8
Total units sold for 3 Product of North is 382.0
Total units sold for 4 Product of North is 89.4
Total units sold for 5 Product of North is 255.0
Total units sold for 6 Product of North is 53.0
--------------------------------------------------
Total units sold for 1 Product of South is 159.0
Total units sold for 2 Product of South is 93.8
Total units sold for 3 Product of South is 306.0
Total units sold for 4 Product of South is 70.0
Total units sold for 5 Product of South is 206.0
Total units sold for 6 Product of South is 49.0


## Task-7
North hub had some customer returns during this window. Subtract the total number of units returned (from `return_log_north`) from product 0's total in your North hub result from Task 6, to get its real net total. Print the corrected value.

In [9]:
Total_Units_Sold_North_Per_Product_copy = Total_Units_Sold_North_Per_Product.copy()
Total_Units_Sold_North_Per_Product_copy[0] = Total_Units_Sold_North_Per_Product[0] - np.abs(np.sum(Return_Log_North))
for i in range(6):
    print(f"The Corrected Value of  {i+1} Product of North is {Total_Units_Sold_North_Per_Product_copy[i]}")

The Corrected Value of  1 Product of North is 194.8
The Corrected Value of  2 Product of North is 128.8
The Corrected Value of  3 Product of North is 382.0
The Corrected Value of  4 Product of North is 89.4
The Corrected Value of  5 Product of North is 255.0
The Corrected Value of  6 Product of North is 53.0


## Task-8
Work out each product's profit margin by subtracting `cost_price` from `sell_price`. Print the result.

In [10]:
Product_Profit_Margin = Sell_Price - Cost_Price
for i in range(len(Product_Profit_Margin)):
    print(f"Profit Margin for Product {i+1} is - {np.ceil(Product_Profit_Margin[i])}")

Profit Margin for Product 1 is - 60.0
Profit Margin for Product 2 is - 100.0
Profit Margin for Product 3 is - 30.0
Profit Margin for Product 4 is - 160.0
Profit Margin for Product 5 is - 69.0
Profit Margin for Product 6 is - 40.0


## Task-9
Using the totals from Task 6 (with North's product 0 corrected as in Task 7) and the margins from Task 8, calculate each hub's total profit per product. Print both results.

In [11]:
Total_ProfiT_Per_North = Total_Units_Sold_North_Per_Product_copy * Product_Profit_Margin
for i in range(len(Product_Profit_Margin)):
    print(f"The Total Profit of Product {i+1} of North Hub is - {Total_ProfiT_Per_North[i]}")

print("-"*50)

Total_ProfiT_Per_South = Total_Units_Sold_South_Per_Product * Product_Profit_Margin
for i in range(len(Product_Profit_Margin)):
    print(f"The Total Profit of Product {i+1} of South Hub is - {Total_ProfiT_Per_South[i]}")

The Total Profit of Product 1 of North Hub is - 11688.0
The Total Profit of Product 2 of North Hub is - 12878.712000000003
The Total Profit of Product 3 of North Hub is - 11456.179999999998
The Total Profit of Product 4 of North Hub is - 14304.0
The Total Profit of Product 5 of North Hub is - 17595.0
The Total Profit of Product 6 of North Hub is - 2119.4700000000003
--------------------------------------------------
The Total Profit of Product 1 of South Hub is - 9540.0
The Total Profit of Product 2 of South Hub is - 9379.062
The Total Profit of Product 3 of South Hub is - 9176.939999999999
The Total Profit of Product 4 of South Hub is - 11200.0
The Total Profit of Product 5 of South Hub is - 14214.0
The Total Profit of Product 6 of South Hub is - 1959.5100000000004


## Task-10
For each hub separately, find which product generated the most profit that window, and print that product's row number and its profit value.

In [12]:
Max_Profit_North = np.max(Total_ProfiT_Per_North)
print("The Max Profit From North Hub is -",Max_Profit_North)
Max_Profit_North_Position = np.argmax(Total_ProfiT_Per_North)
print("The Position of Max Profit From North Hub is -",Max_Profit_North_Position)

print("-"*50)

Max_Profit_South = np.max(Total_ProfiT_Per_South)
print("The Max Profit From South Hub is -",Max_Profit_South)
Max_Profit_South_Position = np.argmax(Total_ProfiT_Per_South)
print("The Position of Max Profit From South Hub is -",Max_Profit_South_Position)

The Max Profit From North Hub is - 17595.0
The Position of Max Profit From North Hub is - 4
--------------------------------------------------
The Max Profit From South Hub is - 14214.0
The Position of Max Profit From South Hub is - 4


## Task-11
Stack the two cleaned hub arrays from Task 5 into a single combined table, North's products first, then South's. Print the shape of the result.

In [40]:
Combined_Table = np.vstack((Replacing_With_Mean_North,Replacing_With_Mean_South))
print("The Combine Table of Cleaned Hub of North and South Table :-")
print(Combined_Table)
print("The Shape of Combined Table is -",Combined_Table.shape)

The Combine Table of Cleaned Hub of North and South Table :-
[[18.  20.  22.  19.  21.  17.8 23.  20.  19.  22. ]
 [12.  10.  11.  13.  20.8 12.  14.  13.  12.  11. ]
 [35.  38.  36.  40.  42.  39.  37.  41.  38.  36. ]
 [ 8.   7.   9.   8.   6.   7.  20.4  8.   9.   7. ]
 [25.  27.  24.  26.  28.  25.  23.  24.  26.  27. ]
 [ 5.   6.   4.   5.   7.   6.   5.   4.   6.   5. ]
 [15.  17.  16.  18.  15.  14.  16.  17.  15.  16. ]
 [ 9.   8.  15.8 10.   9.   7.   8.   9.  10.   8. ]
 [30.  32.  31.  29.  33.  30.  28.  31.  32.  30. ]
 [ 6.   5.   7.   6.  17.   5.   6.   7.   6.   5. ]
 [20.  22.  21.  19.  23.  20.  18.  21.  22.  20. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]
The Shape of Combined Table is - (12, 10)


## Task-12
Add `new_hub_week` onto the combined table from Task 11 as a new block of rows for a 3rd hub. Print the new shape.

In [39]:
New_Block = np.vstack((Combined_Table,New_Hub_Week))
print("The Combined Table After Adding New Hub Week :-")
print(New_Block)
print("The Shape of Combined Table now -",New_Block.shape)

The Combined Table After Adding New Hub Week :-
[[18.  20.  22.  19.  21.  17.8 23.  20.  19.  22. ]
 [12.  10.  11.  13.  20.8 12.  14.  13.  12.  11. ]
 [35.  38.  36.  40.  42.  39.  37.  41.  38.  36. ]
 [ 8.   7.   9.   8.   6.   7.  20.4  8.   9.   7. ]
 [25.  27.  24.  26.  28.  25.  23.  24.  26.  27. ]
 [ 5.   6.   4.   5.   7.   6.   5.   4.   6.   5. ]
 [15.  17.  16.  18.  15.  14.  16.  17.  15.  16. ]
 [ 9.   8.  15.8 10.   9.   7.   8.   9.  10.   8. ]
 [30.  32.  31.  29.  33.  30.  28.  31.  32.  30. ]
 [ 6.   5.   7.   6.  17.   5.   6.   7.   6.   5. ]
 [20.  22.  21.  19.  23.  20.  18.  21.  22.  20. ]
 [16.   3.   4.   3.   5.   4.   3.   4.   3.   4. ]
 [14.  16.  15.  17.  14.  13.  15.  16.  14.  15. ]
 [ 7.   6.   8.   7.   6.   5.   7.   8.   7.   6. ]
 [28.  30.  29.  27.  31.  28.  26.  29.  30.  28. ]
 [ 5.   4.   6.   5.   4.   3.   5.   6.   5.   4. ]
 [18.  20.  19.  17.  21.  18.  16.  19.  20.  18. ]
 [ 3.   4.   2.   3.   5.   4.   3.   2.   4.   3. 

## Task-13
From the table in Task 12, remove South hub's entire block of rows in a single operation. Print the resulting shape.

In [38]:
Removing_South = np.delete(New_Block,slice(6,12),axis=0)
print("The Combined Table after Removing South Cleaned Hub :-")
print(Removing_South)

The Combined Table after Removing South Cleaned Hub :-
[[18.  20.  22.  19.  21.  17.8 23.  20.  19.  22. ]
 [12.  10.  11.  13.  20.8 12.  14.  13.  12.  11. ]
 [35.  38.  36.  40.  42.  39.  37.  41.  38.  36. ]
 [ 8.   7.   9.   8.   6.   7.  20.4  8.   9.   7. ]
 [25.  27.  24.  26.  28.  25.  23.  24.  26.  27. ]
 [ 5.   6.   4.   5.   7.   6.   5.   4.   6.   5. ]
 [14.  16.  15.  17.  14.  13.  15.  16.  14.  15. ]
 [ 7.   6.   8.   7.   6.   5.   7.   8.   7.   6. ]
 [28.  30.  29.  27.  31.  28.  26.  29.  30.  28. ]
 [ 5.   4.   6.   5.   4.   3.   5.   6.   5.   4. ]
 [18.  20.  19.  17.  21.  18.  16.  19.  20.  18. ]
 [ 3.   4.   2.   3.   5.   4.   3.   2.   4.   3. ]]


## Task-14
From each of the two cleaned hub arrays, pull out only the last 4 days for every product. Print both results.

In [37]:
Pull_Out_North = Replacing_With_Mean_North[:,6:11]
print("The Last 4 Days of Every Product of North Cleaned Hub :-")
print(Pull_Out_North)

print("-"*50)

Pull_Out_South = Replacing_With_Mean_North[:,6:11]
print("The Last 4 Days of Every Product of South Cleaned Hub :-")
print(Pull_Out_South)

The Last 4 Days of Every Product of North Cleaned Hub :-
[[23.  20.  19.  22. ]
 [14.  13.  12.  11. ]
 [37.  41.  38.  36. ]
 [20.4  8.   9.   7. ]
 [23.  24.  26.  27. ]
 [ 5.   4.   6.   5. ]]
--------------------------------------------------
The Last 4 Days of Every Product of South Cleaned Hub :-
[[23.  20.  19.  22. ]
 [14.  13.  12.  11. ]
 [37.  41.  38.  36. ]
 [20.4  8.   9.   7. ]
 [23.  24.  26.  27. ]
 [ 5.   4.   6.   5. ]]


## Task-15
From `hub_stock`, find every position where the value is below `10`. Print the positions, then print a copy of `hub_stock` where every value below `10` is replaced with `12`.

In [36]:
Rows,Columns = np.where(Hub_Stock < 10)
print("Rows -",Rows)
print("Columns -",Columns)

print("-"*50)

Hub_Stock_Copy = Hub_Stock.copy()
Hub_Stock_Copy = np.where(Hub_Stock_Copy < 10 , 12 , Hub_Stock_Copy)
print("The Hub stock Copy After where every value below 10 is replaced with 12 :-")
print(Hub_Stock_Copy)

Rows - []
Columns - []
--------------------------------------------------
The Hub stock Copy After where every value below 10 is replaced with 12 :-
[[15 20 40 20 20 20]
 [10 20 35 20 18 20]]


## Task-16
In `hub_stock` directly (not a copy), set every value below `10` to exactly `20`, using a condition, without using the replace-and-return approach from Task 15.


In [20]:
Hub_Stock[Hub_Stock < 10] = 20
print("Hub Stock After set every value below 10 to exactly 20 -", Hub_Stock)

Hub Stock After set every value below 10 to exactly 20 - [[15 20 40 20 20 20]
 [10 20 35 20 18 20]]


## Task-17
In your cleaned `hub_south_sales` from Task 5, set product row index 5's entire 10 days to `0`, treating it as a recall.

In [34]:
Replacing_With_Mean_South[5,:] = 0
print("Hub South Sales After set product row index 5's entire 10 days to 0 -")
print(Replacing_With_Mean_South)

Hub South Sales After set product row index 5's entire 10 days to 0 -
[[15.  17.  16.  18.  15.  14.  16.  17.  15.  16. ]
 [ 9.   8.  15.8 10.   9.   7.   8.   9.  10.   8. ]
 [30.  32.  31.  29.  33.  30.  28.  31.  32.  30. ]
 [ 6.   5.   7.   6.  17.   5.   6.   7.   6.   5. ]
 [20.  22.  21.  19.  23.  20.  18.  21.  22.  20. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]


## Task-18
Print each distinct promo code used, along with how many times each one appears in `promo_codes`.

In [28]:
Distinct_Promo_Code = np.unique(Promo_Codes,return_counts=True)
print("Each distinct promo code is -",Distinct_Promo_Code[0])
print("Times each one Distinct appears in promo_codes -",Distinct_Promo_Code[1])

Each distinct promo code is - ['BIGDEAL' 'CLEARANCE' 'FESTIVE' 'WELCOME5']
Times each one Distinct appears in promo_codes - [1 2 3 4]


## Task-19
Check `promo_codes` against `flagged_promo` and print the exact position(s) where a flagged code was used.

In [32]:
Checking = np.where(np.isin(Promo_Codes,Flagged_Promo))
print("the exact position(s) where a flagged code was used is -",Checking[0])

the exact position(s) where a flagged code was used is - [6]


## Task-20
Using each hub's total units (sum across all 6 products from Task 6, North corrected as in Task 7), arrange the two hubs from highest-selling to lowest-selling, and print the result.

In [47]:
High_To_Low_North = np.sort(Total_Units_Sold_North_Per_Product_copy)[::-1]
for i in range(6):
    print(f"The Total Units of {i+1} Product of North is - {High_To_Low_North[i]}")

print("-"*50)

High_To_Low_South = np.sort(Total_Units_Sold_South_Per_Product)[::-1]
for i in range(6):
    print(f"The Total Units of {i+1} Product of South is - {High_To_Low_South[i]}")

The Total Units of 1 Product of North is - 382.0
The Total Units of 2 Product of North is - 255.0
The Total Units of 3 Product of North is - 194.8
The Total Units of 4 Product of North is - 128.8
The Total Units of 5 Product of North is - 89.4
The Total Units of 6 Product of North is - 53.0
--------------------------------------------------
The Total Units of 1 Product of South is - 306.0
The Total Units of 2 Product of South is - 206.0
The Total Units of 3 Product of South is - 159.0
The Total Units of 4 Product of South is - 93.8
The Total Units of 5 Product of South is - 70.0
The Total Units of 6 Product of South is - 49.0


## Task-21
Using your cleaned `hub_north_sales` from Task 5, find the total sales for each day (add up all 6 products for that day), then find which specific days had a total above North hub's own average day total.

In [58]:
Total_Sales_Each_Day = np.sum(Replacing_With_Mean_North, axis=0)

for i in range(10):
    print(f"Total sales for Day {i+1} of North is - {Total_Sales_Each_Day[i]}")

print("-" * 50)

Avg_Daily = np.mean(Total_Sales_Each_Day)
print("North hub's own average day total is -", Avg_Daily)

Specific_Days = np.where(Total_Sales_Each_Day > Avg_Daily)[0]
print("Days above average:", Specific_Days + 1)

Total sales for Day 1 of North is - 103.0
Total sales for Day 2 of North is - 108.0
Total sales for Day 3 of North is - 106.0
Total sales for Day 4 of North is - 111.0
Total sales for Day 5 of North is - 124.8
Total sales for Day 6 of North is - 106.8
Total sales for Day 7 of North is - 122.4
Total sales for Day 8 of North is - 110.0
Total sales for Day 9 of North is - 110.0
Total sales for Day 10 of North is - 108.0
--------------------------------------------------
North hub's own average day total is - 111.0
Days above average: [5 7]


## Task-22
Print a final summary showing, for each hub: total units sold (all products combined, North corrected for returns) and total profit (all products combined).

In [66]:
North_Hub_Units = np.sum(Total_Units_Sold_North_Per_Product_copy)
print("Total Units Sold From North Hub (all products combined) -",North_Hub_Units)
South_Hub_Units = np.sum(Total_Units_Sold_South_Per_Product)
print("Total Units Sold From South Hub (all products combined) -",South_Hub_Units)

print("-" * 50)

North_Hub_Profit = np.ceil(np.sum(Total_ProfiT_Per_North))
print("Total Profit Of North Hub -",North_Hub_Profit)
South_Hub_Profit = np.ceil(np.sum(Total_ProfiT_Per_South))
print("Total Profit Of North Hub -",South_Hub_Profit)

Total Units Sold From North Hub (all products combined) - 1103.0
Total Units Sold From South Hub (all products combined) - 883.8
--------------------------------------------------
Total Profit Of North Hub - 70042.0
Total Profit Of North Hub - 55470.0
