In [1]:
import numpy as np

In [2]:
# Sample Data

Store0_sales = np.array([
    [45,50,48,52,60,55,58],
    [30,28,32,35,33,31,29],
    [70,75,72,80,78,76,74],
    [20,22,19,21,25,23,20],
    [15,18,16,17,19,20,18]
])

Store1_sales = np.array([
    [55,60,58,62,65,63,61],
    [40,38,42,45,43,41,39],
    [90,95,92,540,98,96,94],
    [25,27,24,26,28,25,23],
    [np.nan,20,18,19,21,22,20]
])

Store2_sales = np.array([
    [35,38,36,40,42,39,37],
    [np.nan,np.nan,28,30,29,27,26],
    [60,58,62,65,63,61,59],
    [15,17,14,16,18,15,14],
    [10,12,11,13,np.nan,14,12]
])
# each array: rows = 5 products, columns = 7 days

Prices = np.array([25.50, 40.00, 15.75, 60.20, 33.10])
Stock = np.array([
    [12, 8, 25, 5, 30],
    [9, 15, 6, 22, 4],
    [18, 3, 40, 7, 11]
])
# rows = 3 stores, columns = 5 products

Discount_codes = np.array(["SAVE10","WELCOME","SAVE10","FLASH","WELCOME","SAVE10","FLASH20"])
Flagged_codes = np.array(["FLASH20","SCAM50"])

New_store_week = np.array([
    [42,45,40,44,46,43,41],
    [33,31,35,32,34,30,29],
    [65,68,63,70,67,66,64],
    [18,20,17,19,21,18,16],
    [22,24,20,23,25,22,21]
])
# a 4th store's weekly sheet, same layout as the others

## Task-1
Print the shape, number of dimensions, and total element count of `store0_sales`, `store1_sales`, and `store2_sales`. Then print the shape of `prices`, `stock`, and `new_store_week`.

In [3]:
Shape_1 = Store0_sales.shape
Shape_2 = Store1_sales.shape
Shape_3 = Store2_sales.shape

Shape_4 = Prices.shape
Shape_5 = Stock.shape
Shape_6 = New_store_week.shape

Dimension_1 = Store0_sales.ndim
Dimension_2 = Store1_sales.ndim
Dimension_3 = Store2_sales.ndim

Total_Element_1 = Store0_sales.size
Total_Element_2 = Store1_sales.size
Total_Element_3 = Store2_sales.size

print("Shape of Store-1 Data is -",Shape_1)
print("Shape of Store-2 Data is -",Shape_2)
print("Shape of Store-3  Data is -",Shape_3)

print("-"*50)

print("Shape of Prices Data is -",Shape_4)
print("Shape of New Store Week Data is -",Shape_5)

print("-"*50)

print("Dimension of Store-1 Data is -",Dimension_1)
print("Dimension of Store-2 Data is -",Dimension_2)
print("Dimension of Store-3 Data is -",Dimension_3)

print("-"*50)

print("Total Element in Store 1 Data -",Total_Element_1)
print("Total Element in Store 2 Data -",Total_Element_2)
print("Total Element in Store 3 Data -",Total_Element_3)

Shape of Store-1 Data is - (5, 7)
Shape of Store-2 Data is - (5, 7)
Shape of Store-3  Data is - (5, 7)
--------------------------------------------------
Shape of Prices Data is - (5,)
Shape of New Store Week Data is - (3, 5)
--------------------------------------------------
Dimension of Store-1 Data is - 2
Dimension of Store-2 Data is - 2
Dimension of Store-3 Data is - 2
--------------------------------------------------
Total Element in Store 1 Data - 35
Total Element in Store 2 Data - 35
Total Element in Store 3 Data - 35


## Task-2
Find the value in `store1_sales` that is far larger than everything around it — a clear data-entry mistake — and print its exact row and column position.

In [4]:
Max_Value = np.nanmax(Store1_sales)

Rows, Column = np.where(Store1_sales == Max_Value)

print("Maximum Value from Store-2 Sales Data is -", Max_Value)
print("Row Index is -", Rows)
print("Column Index is -", Column)

Maximum Value from Store-2 Sales Data is - 540.0
Row Index is - [2]
Column Index is - [3]


## Task-3
Make a copy of `store1_sales`. In that copy, replace the value you found in Task 2 with the missing-value marker instead of a number, so it's treated the same as the other gaps in the data.

In [5]:
Store_2_Sales = Store1_sales.copy()

Missing_Value = np.where(np.isnan(Store_2_Sales),Max_Value,Store_2_Sales)
print("The Store 1 Sales Data after inserting missing Values -",Missing_Value)

The Store 1 Sales Data after inserting missing Values - [[ 55.  60.  58.  62.  65.  63.  61.]
 [ 40.  38.  42.  45.  43.  41.  39.]
 [ 90.  95.  92. 540.  98.  96.  94.]
 [ 25.  27.  24.  26.  28.  25.  23.]
 [540.  20.  18.  19.  21.  22.  20.]]


## Task-4
Count how many values are missing in `store0_sales`, in your corrected `store1_sales` copy from Task 3, and in `store2_sales` — three separate counts.

In [6]:
Total_Nan_Values_1 = np.sum(np.isnan(Store0_sales))
print("Total Nan Values in Store 1 Sales Data is -",Total_Nan_Values_1)

Total_Nan_Values_2 = np.sum(np.isnan(Store_2_Sales))
print("Total Nan Values in Store 2 Sales Copy Data is -",Total_Nan_Values_2)

Total_Nan_Values_3 = np.sum(np.isnan(Store2_sales))
print("Total Nan Values in Store 3 Sales Data is -",Total_Nan_Values_3)

Total Nan Values in Store 1 Sales Data is - 0
Total Nan Values in Store 2 Sales Copy Data is - 1
Total Nan Values in Store 3 Sales Data is - 3


## Task-5
Make a cleaned copy of each of the three store arrays. For every product (row) in each store, fill its missing days with that row's own weekly average, ignoring the gaps while calculating it. No missing values should remain anywhere in any of the three results.

In [7]:
Store_1_Sales = Store0_sales.copy()
Store_3_Sales = Store2_sales.copy()

Replacing_1 = np.where(np.isnan(Store_1_Sales),np.nanmean(Store_1_Sales),Store_1_Sales)
print("Store 1 Sales Data after replacing nan values with that row average -",Replacing_1)

Replacing_2 = np.where(np.isnan(Store_2_Sales),np.nanmean(Store_2_Sales),Store_2_Sales)
print("Store 2 Sales Data after replacing nan values with that row average -",Replacing_2)

Replacing_3 = np.where(np.isnan(Store_3_Sales),np.nanmean(Store_3_Sales),Store_3_Sales)
print("Store 1 Sales Data after replacing nan values with that row average -",Replacing_3)

Store 1 Sales Data after replacing nan values with that row average - [[45. 50. 48. 52. 60. 55. 58.]
 [30. 28. 32. 35. 33. 31. 29.]
 [70. 75. 72. 80. 78. 76. 74.]
 [20. 22. 19. 21. 25. 23. 20.]
 [15. 18. 16. 17. 19. 20. 18.]]
Store 2 Sales Data after replacing nan values with that row average - [[ 55.          60.          58.          62.          65.
   63.          61.        ]
 [ 40.          38.          42.          45.          43.
   41.          39.        ]
 [ 90.          95.          92.         540.          98.
   96.          94.        ]
 [ 25.          27.          24.          26.          28.
   25.          23.        ]
 [ 62.20588235  20.          18.          19.          21.
   22.          20.        ]]
Store 1 Sales Data after replacing nan values with that row average - [[35.   38.   36.   40.   42.   39.   37.  ]
 [31.75 31.75 28.   30.   29.   27.   26.  ]
 [60.   58.   62.   65.   63.   61.   59.  ]
 [15.   17.   14.   16.   18.   15.   14.  ]
 [10.   12.  

## Task-6
Using the three cleaned arrays from Task 5, calculate each store's total weekly units sold for every product (add up all 7 days per row). Print all three results.

In [8]:
Weekly_Unit_Sold_1 = np.sum(Replacing_1,axis=1)
for i in range(5):
    print(f"Total Weekly Units Sold of {i+1} Product Of Store-1 is - {Weekly_Unit_Sold_1[i]}")

print("-"*50)

Weekly_Unit_Sold_2 = np.sum(Replacing_2,axis=1)
for i in range(5):
    print(f"Total Weekly Units Sold of {i+1} Product Of Store-2 is - {Weekly_Unit_Sold_2[i]}")

print("-"*50)

Weekly_Unit_Sold_3 = np.sum(Replacing_3,axis=1)
for i in range(5):
    print(f"Total Weekly Units Sold for {i+1} Product Of Store-2 is - {Weekly_Unit_Sold_3[i]}")

Total Weekly Units Sold of 1 Product Of Store-1 is - 368.0
Total Weekly Units Sold of 2 Product Of Store-1 is - 218.0
Total Weekly Units Sold of 3 Product Of Store-1 is - 525.0
Total Weekly Units Sold of 4 Product Of Store-1 is - 150.0
Total Weekly Units Sold of 5 Product Of Store-1 is - 123.0
--------------------------------------------------
Total Weekly Units Sold of 1 Product Of Store-2 is - 424.0
Total Weekly Units Sold of 2 Product Of Store-2 is - 288.0
Total Weekly Units Sold of 3 Product Of Store-2 is - 1105.0
Total Weekly Units Sold of 4 Product Of Store-2 is - 178.0
Total Weekly Units Sold of 5 Product Of Store-2 is - 182.20588235294116
--------------------------------------------------
Total Weekly Units Sold for 1 Product Of Store-2 is - 267.0
Total Weekly Units Sold for 2 Product Of Store-2 is - 203.5
Total Weekly Units Sold for 3 Product Of Store-2 is - 428.0
Total Weekly Units Sold for 4 Product Of Store-2 is - 109.0
Total Weekly Units Sold for 5 Product Of Store-2 is - 

## Task-7
Using the totals from Task 6, calculate each store's weekly revenue per product by pairing each product's total with its matching price from `prices`. Print all three revenue results.

In [9]:
Revenue_Store_1 = Weekly_Unit_Sold_1 * Prices
Revenue_Store_2 = Weekly_Unit_Sold_2 * Prices
Revenue_Store_3 = Weekly_Unit_Sold_3 * Prices
for i in range(5):
    print(f"Total Revenue of {i+1} Product Of Store-1 is - {Revenue_Store_1[i]}")

print("-"*50)

for i in range(5):
    print(f"Total Revenue of {i+1} Product Of Store-1 is - {Revenue_Store_2[i]}")

print("-"*50)

for i in range(5):
    print(f"Total Revenue of {i+1} Product Of Store-1 is - {Revenue_Store_3[i]}")

Total Revenue of 1 Product Of Store-1 is - 9384.0
Total Revenue of 2 Product Of Store-1 is - 8720.0
Total Revenue of 3 Product Of Store-1 is - 8268.75
Total Revenue of 4 Product Of Store-1 is - 9030.0
Total Revenue of 5 Product Of Store-1 is - 4071.3
--------------------------------------------------
Total Revenue of 1 Product Of Store-1 is - 10812.0
Total Revenue of 2 Product Of Store-1 is - 11520.0
Total Revenue of 3 Product Of Store-1 is - 17403.75
Total Revenue of 4 Product Of Store-1 is - 10715.6
Total Revenue of 5 Product Of Store-1 is - 6031.014705882352
--------------------------------------------------
Total Revenue of 1 Product Of Store-1 is - 6808.5
Total Revenue of 2 Product Of Store-1 is - 8140.0
Total Revenue of 3 Product Of Store-1 is - 6741.0
Total Revenue of 4 Product Of Store-1 is - 6561.8
Total Revenue of 5 Product Of Store-1 is - 3434.125


## Task-8
For each store separately, find which product earned the most revenue that week, and print that product's row number and its revenue value.

In [10]:
Row_Number_1 = np.argmax(Revenue_Store_1)
Max_Revenue_1 = Revenue_Store_1[Row_Number_1]
print(f"Row Number for Max_Revenue for Store-1 is {Row_Number_1 + 1} and their Value is {Max_Revenue_1}") 

print("-"*50)

Row_Number_2 = np.argmax(Revenue_Store_2)
Max_Revenue_2 = Revenue_Store_2[Row_Number_2]
print(f"Row Number for Max_Revenue for Store-2 is {Row_Number_2 + 1} and their Value is {Max_Revenue_2}") 

print("-"*50)

Row_Number_3 = np.argmax(Revenue_Store_3)
Max_Revenue_3 = Revenue_Store_3[Row_Number_3]
print(f"Row Number for Max_Revenue for Store-3 is {Row_Number_3 + 1} and their Value is {Max_Revenue_3}")

Row Number for Max_Revenue for Store-1 is 1 and their Value is 9384.0
--------------------------------------------------
Row Number for Max_Revenue for Store-2 is 3 and their Value is 17403.75
--------------------------------------------------
Row Number for Max_Revenue for Store-3 is 2 and their Value is 8140.0


## Task-9
Stack the three cleaned store arrays from Task 5 into a single combined table, store 0's products first, then store 1's, then store 2's. Print the shape of the result.

In [11]:
Store_Combined_Table = np.vstack((Replacing_1,Replacing_2,Replacing_3))
print("Combined Table of 3 store -",Store_Combined_Table)
print("Shape of Combined Table of 3 store -",Store_Combined_Table.shape)

Combined Table of 3 store - [[ 45.          50.          48.          52.          60.
   55.          58.        ]
 [ 30.          28.          32.          35.          33.
   31.          29.        ]
 [ 70.          75.          72.          80.          78.
   76.          74.        ]
 [ 20.          22.          19.          21.          25.
   23.          20.        ]
 [ 15.          18.          16.          17.          19.
   20.          18.        ]
 [ 55.          60.          58.          62.          65.
   63.          61.        ]
 [ 40.          38.          42.          45.          43.
   41.          39.        ]
 [ 90.          95.          92.         540.          98.
   96.          94.        ]
 [ 25.          27.          24.          26.          28.
   25.          23.        ]
 [ 62.20588235  20.          18.          19.          21.
   22.          20.        ]
 [ 35.          38.          36.          40.          42.
   39.          37.        ]
 [ 3

## Task-10
From the combined table in Task 9, pull out only the rows that belong to store 1, and confirm they match your cleaned `store1_sales` from Task 5.

In [12]:
Store_1_Pull = Store_Combined_Table[5:10]
print(Store_1_Pull)

if np.array_equal(Store_1_Pull,Replacing_2):
    print("Yes these 2 arrays are Matching")

[[ 55.          60.          58.          62.          65.
   63.          61.        ]
 [ 40.          38.          42.          45.          43.
   41.          39.        ]
 [ 90.          95.          92.         540.          98.
   96.          94.        ]
 [ 25.          27.          24.          26.          28.
   25.          23.        ]
 [ 62.20588235  20.          18.          19.          21.
   22.          20.        ]]
Yes these 2 arrays are Matching


## Task-11
Add `new_store_week` onto the combined table from Task 9 as a new block of rows for a 4th store. Print the new shape.

In [13]:
Adding_Store_4 = np.append(Store_Combined_Table,New_store_week,axis = 0)
print("Adding Add new_store_week onto the combined table -",Adding_Store_4)
print("The New Shape Afer Adding new store week onto the combined table is -",Adding_Store_4.shape)

Adding Add new_store_week onto the combined table - [[ 45.          50.          48.          52.          60.
   55.          58.        ]
 [ 30.          28.          32.          35.          33.
   31.          29.        ]
 [ 70.          75.          72.          80.          78.
   76.          74.        ]
 [ 20.          22.          19.          21.          25.
   23.          20.        ]
 [ 15.          18.          16.          17.          19.
   20.          18.        ]
 [ 55.          60.          58.          62.          65.
   63.          61.        ]
 [ 40.          38.          42.          45.          43.
   41.          39.        ]
 [ 90.          95.          92.         540.          98.
   96.          94.        ]
 [ 25.          27.          24.          26.          28.
   25.          23.        ]
 [ 62.20588235  20.          18.          19.          21.
   22.          20.        ]
 [ 35.          38.          36.          40.          42.
   39.   

## Task-12
Remove store 1's entire block of rows from the combined table (from Task 9) in a single operation. Print the resulting shape.

In [19]:
Deleting_Store_1 = np.delete(Store_Combined_Table, slice(0, 5), axis=0)
print("Result after Deleting 1's entire block of rows from the combined table",Deleting_Store_1)

Result after Deleting 1's entire block of rows from the combined table [[ 55.          60.          58.          62.          65.
   63.          61.        ]
 [ 40.          38.          42.          45.          43.
   41.          39.        ]
 [ 90.          95.          92.         540.          98.
   96.          94.        ]
 [ 25.          27.          24.          26.          28.
   25.          23.        ]
 [ 62.20588235  20.          18.          19.          21.
   22.          20.        ]
 [ 35.          38.          36.          40.          42.
   39.          37.        ]
 [ 31.75        31.75        28.          30.          29.
   27.          26.        ]
 [ 60.          58.          62.          65.          63.
   61.          59.        ]
 [ 15.          17.          14.          16.          18.
   15.          14.        ]
 [ 10.          12.          11.          13.          31.75
   14.          12.        ]]


## Task-13
From each of the three cleaned store arrays, pull out only the last 3 days for every product. Print all three results.

In [67]:
Store_1_last = Replacing_1[:,4:7]
print("The last 3 days for every product Of store -1 is ",Store_1_last)

print("-"*50)

Store_2_last = Replacing_2[:,4:7]
print("The last 3 days for every product Of store -2 is ",Store_2_last)

print("-"*50)

Store_3_last = Replacing_3[:,4:7]
print("The last 3 days for every product Of store -3 is ",Store_3_last)

The last 3 days for every product Of store -1 is  [[60. 55. 58.]
 [33. 31. 29.]
 [78. 76. 74.]
 [25. 23. 20.]
 [19. 20. 18.]]
--------------------------------------------------
The last 3 days for every product Of store -2 is  [[65. 63. 61.]
 [43. 41. 39.]
 [98. 96. 94.]
 [28. 25. 23.]
 [21. 22. 20.]]
--------------------------------------------------
The last 3 days for every product Of store -3 is  [[42.   39.   37.  ]
 [29.   27.   26.  ]
 [63.   61.   59.  ]
 [18.   15.   14.  ]
 [31.75 14.   12.  ]]


## Task-14
From `stock`, find every position where the value is below `10`. Print the positions, then print a copy of `stock` where every value below `10` is replaced with `10`.

In [32]:
Rows, Columns = np.where(Stock < 10)
print(f"Position where the value is below 10 is\n"
      f"Rows - {Rows}, Columns - {Columns}")

Stock_Copy = Stock.copy()
Replaced_Stock = np.where(Stock < 10,10,Stock)
print("A copy of stock where every value below 10 is replaced with 10 is -",Replaced_Stock)

Position where the value is below 10 is
Rows - [0 0 1 1 1 2 2], Columns - [1 3 0 2 4 1 3]
A copy of stock where every value below 10 is replaced with 10 is - [[12 10 25 10 30]
 [10 15 10 22 10]
 [18 10 40 10 11]]


## Task-15
In `stock` directly (not a copy), set every value below `10` to exactly `15`, using a condition, without using the replace-and-return approach from Task 14.

In [37]:
Stock[Stock < 10] = 15
print("Setting every value below 10 to exactly 15 -",Stock)

Setting every value below 10 to exactly 15 - [[12 15 25 15 30]
 [15 15 15 22 15]
 [18 15 40 15 11]]


## Task-16
In your cleaned `store1_sales` from Task 5, set the last product's entire row (all 7 days) to `0`, treating it as a recall — the product is being pulled from sale.

In [38]:
Replacing_2_recalled = Replacing_2.copy()
Replacing_2_recalled[4] = 0
print("Setting the last product's entire row (all 7 days) to 0 -",Replacing_2_recalled)

Setting the last product's entire row (all 7 days) to 0 - [[ 55.  60.  58.  62.  65.  63.  61.]
 [ 40.  38.  42.  45.  43.  41.  39.]
 [ 90.  95.  92. 540.  98.  96.  94.]
 [ 25.  27.  24.  26.  28.  25.  23.]
 [  0.   0.   0.   0.   0.   0.   0.]]


## Task-17
Print each distinct discount code used, along with how many times each one appears in `discount_codes`.

In [40]:
Unique_Codes, Code_Counts = np.unique(Discount_codes,return_counts=True)

print("Unique Discount Codes -", Unique_Codes)
print("Count of Each Discount Code -", Code_Counts)

Unique Discount Codes - ['FLASH' 'FLASH20' 'SAVE10' 'WELCOME']
Count of Each Discount Code - [1 1 3 2]


## Task-18
Check `discount_codes` against `flagged_codes` and print the exact position(s) in `discount_codes` where a flagged code was used.

In [44]:
Check = np.where(np.isin(Discount_codes,Flagged_codes))
print("The exact position(s) in discount_codes where a flagged code was used -",Check)

he exact position(s) in discount_codes where a flagged code was used - (array([6]),)


## Task-19
Using each store's total weekly units (sum across all 5 products from Task 6), arrange the three stores from highest-selling to lowest-selling, and print the store numbers in that order.

In [52]:
Store_Total_1 = np.sum(Weekly_Unit_Sold_1)
Store_Total_2 = np.sum(Weekly_Unit_Sold_2)
Store_Total_3 = np.sum(Weekly_Unit_Sold_3)

print("The total units sold by store-1 for the entire week-",Store_Total_1)
print("The total units sold by store-2 for the entire week-",Store_Total_2)
print("The total units sold by store-3 for the entire week-",Store_Total_3)

All_Store = np.array([Store_Total_1,Store_Total_2,Store_Total_3])
Des = np.sort(All_Store)[::-1]
print("The three stores from highest-selling to lowest-selling -",Des)

Store_Number = np.argsort(All_Store)[::-1]
print("The store numbers in Highest to Lowest Selling Order -",Store_Number)

The total units sold by store-1 for the entire week- 1384.0
The total units sold by store-2 for the entire week- 2177.205882352941
The total units sold by store-3 for the entire week- 1111.25
The three stores from highest-selling to lowest-selling - [2177.20588235 1384.         1111.25      ]
The store numbers in Highest to Lowest Selling Order - [1 0 2]


## Task-20
Using your cleaned `store0_sales` from Task 5, find the total sales for each day (add up all 5 products for that day), then find which specific days had a total above that store's own average day total.

In [63]:
Total_Day_Wise = np.sum(Replacing_1,axis=0)
Avg_Day_Sales = np.mean(Total_Day_Wise)

for i in range(0,7):
    print(f"The Total Sales for Day {i+1} is - {Total_Day_Wise[i]}")

print("The average day total is -",Avg_Day_Sales)
Specific_Days = np.where(Total_Day_Wise > Avg_Day_Sales)
print("Days had a total above that store's own average day total -",Specific_Days[0]+1)

The Total Sales for Day 1 is - 180.0
The Total Sales for Day 2 is - 193.0
The Total Sales for Day 3 is - 187.0
The Total Sales for Day 4 is - 205.0
The Total Sales for Day 5 is - 215.0
The Total Sales for Day 6 is - 205.0
The Total Sales for Day 7 is - 199.0
The average day total is - 197.71428571428572
Days had a total above that store's own average day total - [4 5 6 7]


## Task-21
 Print a final summary showing, for each store: total weekly units sold (all products combined) and total weekly revenue (all products combined).

In [66]:
print("For Store - 1")
Total_weekly_units_sold_1 = np.sum(Weekly_Unit_Sold_1)
Total_Weekely_Revenue_1 = np.sum(Revenue_Store_1)
print("The Total Weekely Units Sold of Store-1 -",Total_weekly_units_sold_1)
print("The Total Weekly Revenue Sold of Store-1 -",Total_Weekely_Revenue_1)

print("-"*50)

print("For Store - 2")
Total_weekly_units_sold_2 = np.sum(Weekly_Unit_Sold_2)
Total_Weekely_Revenue_2 = np.sum(Revenue_Store_2)
print("The Total Weekely Units Sold of Store-2 -",Total_weekly_units_sold_2)
print("The Total Weekly Revenue Sold of Store-2 -",Total_Weekely_Revenue_2)

print("-"*50)

print("For Store - 3")
Total_weekly_units_sold_3 = np.sum(Weekly_Unit_Sold_3)
Total_Weekely_Revenue_3 = np.sum(Revenue_Store_3)
print("The Total Weekely Units Sold of Store-3 -",Total_weekly_units_sold_3)
print("The Total Weekly Revenue Sold of Store-3 -",Total_Weekely_Revenue_3)

For Store - 1
The Total Weekely Units Sold of Store-1 - 1384.0
The Total Weekly Revenue Sold of Store-1 - 39474.05
--------------------------------------------------
For Store - 2
The Total Weekely Units Sold of Store-2 - 2177.205882352941
The Total Weekly Revenue Sold of Store-2 - 56482.36470588235
--------------------------------------------------
For Store - 3
The Total Weekely Units Sold of Store-3 - 1111.25
The Total Weekly Revenue Sold of Store-3 - 31685.425
