In [13]:
import numpy as np

## Part 1 — Sorting

In [14]:
# Sample Data
Weekly_sales = np.array([45, 12, np.nan, 30, 8, 45, 22])
Product_codes = np.array([105, 102, 105, 108, 102, 110, 105])
Product_names = np.array(["Kettle", "Mixer", "Toaster", "Kettle", "Blender"])

### Tasks
1. Arrange `weekly_sales` in ascending order without changing the original array. Print the result.
2. Make a copy of `weekly_sales` called `sales_copy`. Arrange `sales_copy` in ascending order so that the change is permanent on `sales_copy` itself. Print both `sales_copy` and the original `weekly_sales` afterward.
3. Produce a version of `weekly_sales` arranged from highest to lowest.
4. Get the index positions that would arrange `weekly_sales` in ascending order, and print them.
5. From `product_codes`, print only the distinct product codes (no repeats), along with how many distinct codes there are.
6. Print `product_names` arranged in alphabetical order.

In [15]:
# 1
Asc = np.sort(Weekly_sales)
print(Asc)

[ 8. 12. 22. 30. 45. 45. nan]


In [16]:
# 2
Sales_Copy = Weekly_sales.copy()
print("Copy of Weekely Sales (Sales Copy) -",Sales_Copy)

Asc = np.sort(Sales_Copy)
print("Asc of Sales Copy -",Asc)

print("Sales Copy -",Sales_Copy)
print("Weekly Sales -",Weekly_sales)

Copy of Weekely Sales (Sales Copy) - [45. 12. nan 30.  8. 45. 22.]
Asc of Sales Copy - [ 8. 12. 22. 30. 45. 45. nan]
Sales Copy - [45. 12. nan 30.  8. 45. 22.]
Weekly Sales - [45. 12. nan 30.  8. 45. 22.]


In [18]:
# 3
Dsc_Weekly_Sales = np.sort(Weekly_sales)[::-1]
print("Desceding Order of Weekly Sales -",Dsc_Weekly_Sales)

Desceding Order of Weekly Sales - [nan 45. 45. 30. 22. 12.  8.]


In [ ]:
# 4
Index_Position = np.argsort(Weekly_sales)
print("Index Position in Ascending Order -",Index_Position)

In [ ]:
# 5
Distinct_Product_Codes = np.unique(Product_codes)
print("Distinct Product Codes -",Distinct_Product_Codes)

In [ ]:
# 6
Asc_Names = np.sort(Product_names)
print("Product Names in Alphabetical Orders -",Asc_Names)

## Part 2 — Adding Data

In [19]:
# Sample Data
Warehouse_A = np.array([
    [120, 135, 140],
    [80, 95, 90],
    [60, 55, 70]
])
Warehouse_B = np.array([
    [200, 210, 205],
    [150, 160, 155],
    [90, 85, 100]
])
New_month = np.array([[150], [100], [75]])
New_product_row = np.array([[40, 42, 39]])

### Tasks
7. Add `22` to the end of `weekly_sales` without changing the original array. Print the new result, then print the original `weekly_sales` again.
8. Place `18` into `weekly_sales` so that it becomes the 3rd element (position index 2), shifting the rest forward. Print the result.
9. Attach `new_month` onto `warehouse_A` as an additional column. Print the result and its shape.
10. Attach `new_product_row` onto `warehouse_A` as an additional row. Print the result and its shape.
11. Combine `warehouse_A` and `warehouse_B` so that all products from both warehouses appear as separate rows in one array. Print the result and its shape.
12. Combine `warehouse_A` and `warehouse_B` so that each warehouse's matching months sit side by side as extra columns. Print the result and its shape.

In [20]:
# 7
Adding_To_Weekely_Sales = np.append(Weekly_sales,[22])
print("Value Add at the End -",Adding_To_Weekely_Sales)

print("Original Weekely Sales -",Weekly_sales)

Value Add at the End - [45. 12. nan 30.  8. 45. 22. 22.]
Original Weekely Sales - [45. 12. nan 30.  8. 45. 22.]


In [21]:
# 8
Adding_To_Weekely_Sales = np.insert(Weekly_sales,2,18)
print("Value Add at the Position 3 -",Adding_To_Weekely_Sales)

Value Add at the Position 3 - [45. 12. 18. nan 30.  8. 45. 22.]


In [22]:
# 9
Adding_Column = np.hstack((Warehouse_A,New_month))
print("New Data of Warehouse A -",Adding_Column)

Shape = Adding_Column.shape
print("The Shape of new Warehouse A -",Shape)

New Data of Warehouse A - [[120 135 140 150]
 [ 80  95  90 100]
 [ 60  55  70  75]]
The Shape of new Warehouse A - (3, 4)


In [23]:
# 10
Adding_NewRow = np.vstack((Warehouse_A,New_product_row))
print("New Data of Warehouse A -",Adding_NewRow)

Shape = Adding_NewRow.shape
print("The Shape of new Warehouse A -",Shape)

New Data of Warehouse A - [[120 135 140]
 [ 80  95  90]
 [ 60  55  70]
 [ 40  42  39]]
The Shape of new Warehouse A - (4, 3)


In [24]:
# 11
Combining_Warehouses = np.concatenate((Warehouse_A,Warehouse_B),axis=0)
print("The Result of Combining Warehouses as a Seperate Row -",Combining_Warehouses)

Shape = Combining_Warehouses.shape
print("The Shape After Combining Warehouse -",Shape)

The Result of Combining Warehouses as a Seperate Row - [[120 135 140]
 [ 80  95  90]
 [ 60  55  70]
 [200 210 205]
 [150 160 155]
 [ 90  85 100]]
The Shape After Combining Warehouse - (6, 3)


In [25]:
# 12
Combining_Warehouses = np.concatenate((Warehouse_A,Warehouse_B),axis=1)
print("The Result of Combining Warehouses as a side by side as extra columns -",Combining_Warehouses)

Shape = Combining_Warehouses.shape
print("The Shape After Combining Warehouse -",Shape)

The Result of Combining Warehouses as a side by side as extra columns - [[120 135 140 200 210 205]
 [ 80  95  90 150 160 155]
 [ 60  55  70  90  85 100]]
The Shape After Combining Warehouse - (3, 6)


## Part 3 — Filtering
13. From `warehouse_A`, pull out only the values greater than `90`.
14. From `warehouse_A`, pull out only the values that are greater than `60` and, at the same time, less than `140`.
15. From `warehouse_A`, pull out only the values that are either less than `60` or greater than `130`.
16. Find the row/column positions in `warehouse_A` where the value is below `70`.
17. Build a new version of `warehouse_A` where every value below `70` is replaced with `0`, and every other value stays as it is.
18. Given:
Restock_flags = np.array([0, 3, 0, 0, 7, 2, 0])
19. Given:
Flagged_codes = np.array([102, 999])
Check `product_codes` against `flagged_codes` and print which entries in `product_codes` are matches. Then print the actual matching values (not just True/False).

In [33]:
# Sample Data
Restock_flags = np.array([0, 3, 0, 0, 7, 2, 0])
Flagged_codes = np.array([102, 999])

In [26]:
# 13
Filtering_1 = Warehouse_A[Warehouse_A > 90]
print("Values which greater than 90 are -",Filtering_1)

Values which greater than 90 are - [120 135 140  95]


In [27]:
# 14
Filtering_2 = Warehouse_A[(Warehouse_A > 90) & (Warehouse_A < 140)]
print("Values which greater than 90 and less than 140 are -",Filtering_2)

Values which greater than 90 and less than 140 are - [120 135  95]


In [28]:
# 15
Filtering_3 = Warehouse_A[(Warehouse_A < 60) | (Warehouse_A > 130)]
print("Values which either less than 60 or greater than 130 are -",Filtering_3)

Values which either less than 60 or greater than 130 are - [135 140  55]


In [31]:
# 16
Index = np.where(Warehouse_A < 70)
Rows,Columns = Index
print("Rows is -",Rows)
print("Column is -",Columns)

Rows is - [2 2]
Column is - [0 1]


In [36]:
# 17
New_Version = np.where(Warehouse_A < 70 , 0,Warehouse_A)
print("New Version of Warehouse A is -",New_Version)

New Version of Warehouse A is - [[120 135 140]
 [ 80  95  90]
 [  0   0  70]]


In [37]:
# 19
Matching = Product_codes[np.isin(Product_codes,Flagged_codes)]
print("Matching Products are -",Matching)

Matching Products are - [102 102]


## Part 4 — Deleting Data
20. Remove the value at index `1` from `weekly_sales`. Print the result.
21. Remove the values at index `0` and index `3` from `weekly_sales`, both in one single operation. Print the result.
22. Remove the second product's entire row from `warehouse_A`. Print the result and its shape.
23. Remove the first month's entire column from `warehouse_A`. Print the result and its shape.


In [38]:
# 20
Delete_1 = np.delete(Weekly_sales,1)
print("Result after deletion of element from index 1 -",Delete_1)

Result after deletion of element from index 1 - [45. nan 30.  8. 45. 22.]


In [43]:
# 21
Delete_2 = np.delete(Weekly_sales,[0,3])
print("Result after deletion of element from index 1 -",Delete_2)

Result after deletion of element from index 1 - [12. nan  8. 45. 22.]


In [45]:
# 22
Delete_3 = np.delete(Warehouse_A,1,axis=0)
print("Result after deletion of second product's entire row from warehouse_A -",Delete_3)

Shape = Delete_3.shape
print("The Shape of Warehouse A after deletion of second product's entire row from warehouse_A is -",Shape)

Result after deletion of second product's entire row from warehouse_A - [[120 135 140]
 [ 60  55  70]]
The Shape of Warehouse A after deletion of second product's entire row from warehouse_A is - (2, 3)


In [47]:
# 23
Delete_4 = np.delete(Warehouse_A,0,axis=1)
print("Result after deletion of first month's entire column from warehouse_A -",Delete_4)

Shape = Delete_4.shape
print("The Shape of Warehouse A after deletion of first month's entire column from warehouse_A -",Shape)

Result after deletion of first month's entire column from warehouse_A - [[135 140]
 [ 95  90]
 [ 55  70]]
The Shape of Warehouse A after deletion of first month's entire column from warehouse_A - (3, 2)


## Part 5 — Axis Behavior
24. Try to attach `new_product_row` onto `warehouse_A` while leaving out any dimension-related setting. Print the result and its shape.
25. Now attach `new_product_row` onto `warehouse_A` again, but this time make sure it's added as a proper new row rather than merged into one long list. Print the result and its shape.
26. Try removing the element at index `0` from `warehouse_A` while leaving out any dimension-related setting. Print the result and its shape.
27. Now remove index `0` from `warehouse_A` again, but this time make it remove an entire column instead. Print the result and its shape.

In [60]:
# 24
Adding_1 = np.append(Warehouse_A,New_product_row)
print("Result after adding New product row into Warehouse A -", Adding_1)

Shape_1 = Adding_1.shape
print("The Shape after adding New product row into Warehouse A -",Shape_1)

Result after adding New product row into Warehouse A - [120 135 140  80  95  90  60  55  70  40  42  39]
The Shape after adding New product row into Warehouse A - (12,)


In [61]:
# 25
Adding_2 = np.append(Warehouse_A,New_product_row,axis = 0)
print("Result after adding New product row into Warehouse A -",Adding_2)

Shape_2 = Adding_2.shape
print("The Shape after adding New product row into Warehouse A -",Shape_2)

Result after adding New product row into Warehouse A - [[120 135 140]
 [ 80  95  90]
 [ 60  55  70]
 [ 40  42  39]]
The Shape after adding New product row into Warehouse A - (4, 3)


In [64]:
# 26
Delete_1 = np.delete(Warehouse_A,0)
print("Result after Deleting the element at index 0 from warehouse_A -",Delete_1)

Shape_3 = Adding_2.shape
print("The Shape after Deleting the element at index 0 from warehouse_A -",Shape_3)

Result after Deleting the element at index 0 from warehouse_A - [135 140  80  95  90  60  55  70]
The Shape after Deleting the element at index 0 from warehouse_A - (4, 3)


In [65]:
# 27
Delete_2 = np.delete(Warehouse_A,0,axis=1)
print("Result after Deleting the element at index 0 from warehouse_A from axis=1 -",Delete_2)

Shape_4 = Adding_2.shape
print("The Shape after Deleting the element at index 0 from warehouse_A from axis=1 -",Shape_4)

Result after Deleting the element at index 0 from warehouse_A from axis=1 - [[135 140]
 [ 95  90]
 [ 55  70]]
The Shape after Deleting the element at index 0 from warehouse_A from axis=1 - (4, 3)
