In [2]:
import numpy as np

In [3]:
# Sample Data
Monthly_sales = np.array([
    [220, 240, np.nan, 260, 210, 230],
    [110, np.nan, 130, 125, 118, np.nan],
    [340, 355, 360, np.nan, 348, 352],
    [95, 88, 92, 90, np.nan, 85]
])

Prices = np.array([199.99, 349.50, 89.75, 560.20])
Stock  = np.array([34, 12, 58, 9])

Warehouse_X = np.array([
    [50, 55, 60],
    [30, 28, 32],
    [70, 75, 68],
    [20, 22, 19]
])
Warehouse_Y = np.array([
    [90, 95, 92],
    [40, 42, 38],
    [100, 105, 98],
    [25, 27, 24]
])

## Tasks
1. Build `monthly_sales`, `prices`, `stock`, `warehouse_X`, and `warehouse_Y` as shown above. Separately, create: a row of all zeros the same length as one month (for a new store), a 4x6 array of all ones (minimum stock guarantee), a 4x6 array where every value is 25 (reorder threshold), a list of product IDs starting at 201 for 4 products, and a 4x4 identity array (for discount tracking). Print all of them.

2. Print how many dimensions `monthly_sales` has, its shape, its total element count, its data type, and how many bytes one element takes up.

3. Reshape `monthly_sales` into a shape with 6 rows and 4 columns. Separately flatten it into 1D, get a 1D view of it using the other flattening method, and produce its transpose. Print all four results.

4. Using `stock` and `prices`, add a new shipment of `[10, 5, 15, 3]` to `stock`, then remove `2` damaged units from every product in one line, then calculate the total value of the updated stock (price times quantity) for each product.

5. For `prices`, print the mean, median, minimum, maximum, standard deviation, and variance.

In [4]:
# 1
New_Store = np.zeros(6,dtype = int)
print("Sales of a new store in Six Months -",New_Store)

Minimun_stock_guarantee = np.ones(6,dtype = int)
print("Minimum stock guarantee of a new store -",Minimun_stock_guarantee)

Reorder_Threshold = np.full(6,25,dtype=int)
print("Reorder Threshold of a new Store -",Reorder_Threshold)

Product_Id = np.arange(201,205)
print("Product Id of 4 products -",Product_Id)

Discount_Tracking = np.eye(4)
print("Indentity Array for disount Tracking -",Discount_Tracking)

Sales of a new store in Six Months - [0 0 0 0 0 0]
Minimum stock guarantee of a new store - [1 1 1 1 1 1]
Reorder Threshold of a new Store - [25 25 25 25 25 25]
Product Id of 4 products - [201 202 203 204]
Indentity Array for disount Tracking - [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# 2
Dimensions = Monthly_sales.ndim
print("Dimensions of Monthly Sales -",Dimensions)

Shape = Monthly_sales.shape
print("Shape of Monthly Sales is -",Shape)

Total_Element = Monthly_sales.size
print("Total Element Count of Monthly Sales is -",Total_Element)

Dtype = Monthly_sales.dtype
print("Data Type of Monthly Sales is -",Dtype)

Bytes = Monthly_sales.itemsize
print("Bytes of 1 element in Monthly Sales -",Monthly_sales)

Dimensions of Monthly Sales - 2
Shape of Monthly Sales is - (4, 6)
Total Element Count of Monthly Sales is - 24
Data Type of Monthly Sales is - float64
Bytes of 1 element in Monthly Sales - [[220. 240.  nan 260. 210. 230.]
 [110.  nan 130. 125. 118.  nan]
 [340. 355. 360.  nan 348. 352.]
 [ 95.  88.  92.  90.  nan  85.]]


In [6]:
# 3
Reshape = np.reshape(Monthly_sales,(6,4))
print("Reshape of Monthy Sales -",Reshape)

Faltten = Monthly_sales.flatten()
print("The 1D View of Monthly Sales is -",Faltten)

Ravel = Monthly_sales.ravel()
print("The 1D view of Monthly Sales is -",Ravel)

Transpose = Monthly_sales.transpose()
print("Transpose of Monthly Sales is -",Transpose)

Reshape of Monthy Sales - [[220. 240.  nan 260.]
 [210. 230. 110.  nan]
 [130. 125. 118.  nan]
 [340. 355. 360.  nan]
 [348. 352.  95.  88.]
 [ 92.  90.  nan  85.]]
The 1D View of Monthly Sales is - [220. 240.  nan 260. 210. 230. 110.  nan 130. 125. 118.  nan 340. 355.
 360.  nan 348. 352.  95.  88.  92.  90.  nan  85.]
The 1D view of Monthly Sales is - [220. 240.  nan 260. 210. 230. 110.  nan 130. 125. 118.  nan 340. 355.
 360.  nan 348. 352.  95.  88.  92.  90.  nan  85.]
Transpose of Monthly Sales is - [[220. 110. 340.  95.]
 [240.  nan 355.  88.]
 [ nan 130. 360.  92.]
 [260. 125.  nan  90.]
 [210. 118. 348.  nan]
 [230.  nan 352.  85.]]


In [7]:
# 4
New_Stock_After_Ship = Stock + np.array([10, 5, 15, 3])
print("The New Stock after Shipment is -",New_Stock_After_Ship)

New_Stock_After_Removal = Stock - 2
print("The New Stock after removal 2 damaged units from every product -",New_Stock_After_Removal)

Total_Value = New_Stock_After_Removal * Prices
print("Total value of the updated stock (price times quantity) for each product -",Total_Value)

The New Stock after Shipment is - [44 17 73 12]
The New Stock after removal 2 damaged units from every product - [32 10 56  7]
Total value of the updated stock (price times quantity) for each product - [6399.68 3495.   5026.   3921.4 ]


In [8]:
# 5
Mean = np.mean(Prices)
print("The Mean of Prices is -",Mean)

Median = np.median(Prices)
print("The Median of Prices is -",Median)

Min_Price = np.min(Prices)
print("The Min Price is -",Min_Price)

Max_Price = np.max(Prices)
print("The Max Price is -",Max_Price)

Std = np.std(Prices)
print("The Standard Deviation of Price is -",Std)

Variance = np.var(Prices)
print("The Variance of Price is -",Variance)

The Mean of Prices is - 299.86
The Median of Prices is - 274.745
The Min Price is - 89.75
The Max Price is - 560.2
The Standard Deviation of Price is - 176.3244695157198
The Variance of Price is - 31090.318550000007


## Task
6. For `prices`, print a version rounded to the nearest whole number, a version always rounded down, and a version always rounded up. Separately, calculate the square root of each price, and the square of each value in `stock`.

7. Given `changes = np.array([-4, 6, -1, 3])`, print the positive size of each change ignoring direction. Separately, multiply every value in `stock` together into one single number.

8. From `monthly_sales`, get the sales value for product index 2 in month index 4 using direct position access. Get the full row for product index 0. Get the value for the last product in the last month using reverse-position access. Build a 3D array by stacking `warehouse_X` and `warehouse_Y` together, then get Warehouse 2, product index 3, month index 1 from it.

9. From `monthly_sales`, get only the first 2 rows with all columns. Get only the last 3 months for all products. Get every other month across all products. Get columns 1 up to (not including) 4 from `prices`.

10. Arrange `stock` in increasing order without touching the original array.Produce a version of `stock` arranged from highest to lowest. Get the index order that would arrange `stock` from smallest to largest.

In [9]:
# 6
Version_1 = np.round(Prices)
print("A version rounded to the nearest whole number -",Version_1)

Version_2 = np.floor(Prices)
print("A version always rounded down -",Version_2)

Version_3 = np.ceil(Prices)
print("A version always rounded up -",Version_3)

Sqrt = np.sqrt(Stock)
print("Square Root of Stock is -",Sqrt)

Power = np.power(Stock,2)
print("The square of each value in stock is -",Power)

A version rounded to the nearest whole number - [200. 350.  90. 560.]
A version always rounded down - [199. 349.  89. 560.]
A version always rounded up - [200. 350.  90. 561.]
Square Root of Stock is - [5.83095189 3.46410162 7.61577311 3.        ]
The square of each value in stock is - [1156  144 3364   81]


In [10]:
# 7
Changes = np.array([-4, 6, -1, 3])

Positive = np.abs(Changes)
print("The Positive size of each change ignoring direction -",Positive)

Prod = np.prod(Stock)
print("The Product of Stock is -",Prod)

The Positive size of each change ignoring direction - [4 6 1 3]
The Product of Stock is - 212976


In [11]:
# 8
Sales_Values_1 = Monthly_sales[2,4]
print("Sales value for product index 2 in month index 4 -",Sales_Values_1)

Sales_Values_2 = Monthly_sales[0]
print("The full row for product index 0 -",Sales_Values_2)

Sales_Values_3 = Monthly_sales[-1,-1]
print("The value for the last product in the last month -",Sales_Values_3)

Warehouses = np.concatenate((Warehouse_X,Warehouse_Y))
Warehouses = Warehouses.reshape(2,4,3)
print("Join 2 warehouse and make in 3D -",Warehouses)

Index_Value = Warehouses[1,3,1]
print("Value from Warehouse 2, product index 3, month index 1 -",Index_Value)

Sales value for product index 2 in month index 4 - 348.0
The full row for product index 0 - [220. 240.  nan 260. 210. 230.]
The value for the last product in the last month - 85.0
Join 2 warehouse and make in 3D - [[[ 50  55  60]
  [ 30  28  32]
  [ 70  75  68]
  [ 20  22  19]]

 [[ 90  95  92]
  [ 40  42  38]
  [100 105  98]
  [ 25  27  24]]]
Value from Warehouse 2, product index 3, month index 1 - 27


In [12]:
print(Monthly_sales)

[[220. 240.  nan 260. 210. 230.]
 [110.  nan 130. 125. 118.  nan]
 [340. 355. 360.  nan 348. 352.]
 [ 95.  88.  92.  90.  nan  85.]]


In [13]:
# 9
Slicing_1 = Monthly_sales[0:2]
print("Monthly sales of first 2 rows with all columns -",Slicing_1)

Slicing_2 =Monthly_sales[:,-1:-4:-1]
print("Monthly Sales only the last 3 months for all products -",Slicing_2)

Slicing_3 = Monthly_sales[:,0:6:2]
print("Every other month across all products -",Slicing_3)

Monthly sales of first 2 rows with all columns - [[220. 240.  nan 260. 210. 230.]
 [110.  nan 130. 125. 118.  nan]]
Monthly Sales only the last 3 months for all products - [[230. 210. 260.]
 [ nan 118. 125.]
 [352. 348.  nan]
 [ 85.  nan  90.]]
Every other month across all products - [[220.  nan 210.]
 [110. 130. 118.]
 [340. 360. 348.]
 [ 95.  92.  nan]]


In [14]:
# 10
Asc = np.sort(Stock)
print("Stock from Lowest to Highest -",Asc)

Dsc = np.sort(Stock)[::-1]
print("Stock From Highest to Lowest -",Dsc)

Index_Asc = np.argsort(Stock)
print("The index order that would arrange stock from smallest to largest -",Index_Asc)

Stock from Lowest to Highest - [ 9 12 34 58]
Stock From Highest to Lowest - [58 34 12  9]
The index order that would arrange stock from smallest to largest - [3 1 0 2]


## Task
11. Given `product_codes = np.array([301, 305, 301, 310, 305, 301])`, print only the distinct codes and how many distinct codes exist. Given `product_labels = np.array(["Fan", "Cooler", "Fan", "Heater"])`, print them in alphabetical order.

12. Add the value `40` to the end of `stock` without changing the original array. Insert the value `15` into `stock` at position 1, pushing the rest forward.

13. Attach a new column `[[65],[35],[80],[26]]` onto `warehouse_X`. Attach a new row `[[45, 48, 50]]` onto `warehouse_Y`. Print both results with their shapes.

14. Combine `warehouse_X` and `warehouse_Y` so all products from both appear as separate rows in one array. Combine them again so their matching months sit side by side as extra columns. Print both results with shapes.

15. From `warehouse_X`, pull out every value greater than `50`. Then pull out every value that is greater than `20` and, at the same time, less than `70`. Then pull out every value that is either below `25` or above `90`.

In [15]:
# 11
Product_Codes = np.array([301, 305, 301, 310, 305, 301])
Product_Labels = np.array(["Fan", "Cooler", "Fan", "Heater"])

Distinct_Codes = np.unique(Product_Codes)
print("The Distinct Codes are -",Distinct_Codes)

Total_Distinct_codes = np.size(np.unique(Product_Codes))
print("Total Number of Distinct Codes -",Total_Distinct_codes)

Alpha_Order = np.sort(Product_Labels)
print("Alphabetical order of product labels is -",Alpha_Order)

The Distinct Codes are - [301 305 310]
Total Number of Distinct Codes - 3
Alphabetical order of product labels is - ['Cooler' 'Fan' 'Fan' 'Heater']


In [16]:
# 12
Add_Stok = np.append(Stock,40)
print("Adding 40 at the end of the stock -",Add_Stok)

Insert_Stock = np.insert(Stock,0,15)
print("Insert the Value 15 into Stock At Position 1 -",Insert_Stock)

Adding 40 at the end of the stock - [34 12 58  9 40]
Insert the Value 15 into Stock At Position 1 - [15 34 12 58  9]


In [24]:
# 13
New_Column = np.array([[65],[35],[80],[26]])
New_Row = np.array([[45, 48, 50]])

Adding_new_Column = np.hstack((Warehouse_X,New_Column))
print("Adding New Column to the Warehouse X -",Adding_new_Column)
print("Now Shape of Warehouse X is -",Adding_new_Column.shape)

Adding_new_row = np.vstack((Warehouse_Y,New_Row))
print("Adding New Row to the Warehouse Y -",Adding_new_row)
print("Now Shape of Warehouse Y is -",Adding_new_row.shape)

Adding New Column to the Warehouse X - [[50 55 60 65]
 [30 28 32 35]
 [70 75 68 80]
 [20 22 19 26]]
Now Shape of Warehouse X is - (4, 4)
Adding New Row to the Warehouse Y - [[ 90  95  92]
 [ 40  42  38]
 [100 105  98]
 [ 25  27  24]
 [ 45  48  50]]
Now Shape of Warehouse Y is - (5, 3)


In [25]:
# 14
Combine_1 = np.vstack((Warehouse_X,Warehouse_Y))
print("Combine warehouse_X and warehouse_Y as Seprate Rows -",Combine_1)
print("Now Shape after Combine warehouse_X and warehouse_Y as Seprate Rows -",Combine_1.shape)

Combine_2 = np.hstack((Warehouse_X,Warehouse_Y))
print("Combine warehouse_X and warehouse_Y matching months sit side by side as extra columns -",Combine_2)
print("Now Shape after Combine warehouse_X and warehouse_Y  matching months sit side by side as extra column -",Combine_2.shape)

Combine warehouse_X and warehouse_Y as Seprate Rows - [[ 50  55  60]
 [ 30  28  32]
 [ 70  75  68]
 [ 20  22  19]
 [ 90  95  92]
 [ 40  42  38]
 [100 105  98]
 [ 25  27  24]]
Now Shape after Combine warehouse_X and warehouse_Y as Seprate Rows - (8, 3)
Combine warehouse_X and warehouse_Y matching months sit side by side as extra columns - [[ 50  55  60  90  95  92]
 [ 30  28  32  40  42  38]
 [ 70  75  68 100 105  98]
 [ 20  22  19  25  27  24]]
Now Shape after Combine warehouse_X and warehouse_Y  matching months sit side by side as extra column - (4, 6)


In [29]:
# 15
Pull_Over_1 = Warehouse_X[Warehouse_X>50]
Pull_Over_2 = Warehouse_X[Warehouse_X>20]
Pull_Over_3 = Warehouse_X[Warehouse_X<70]
Pull_Over_4 = Warehouse_X[(Warehouse_X<25) | (Warehouse_X>90)]

print("Value that is greater than 50 in Warehouse X is -",Pull_Over_1)
print("Value that is greater than 20 in Warehouse X is -",Pull_Over_2)
print("Value that is less than 70 in Warehouse X is -",Pull_Over_3)
print("Value that is greater than 80 or less than 25 in Warehouse X is -",Pull_Over_4)

Value that is greater than 50 in Warehouse X is - [55 60 70 75 68]
Value that is greater than 20 in Warehouse X is - [50 55 60 30 28 32 70 75 68 22]
Value that is less than 70 in Warehouse X is - [50 55 60 30 28 32 68 20 22 19]
Value that is greater than 80 or less than 25 in Warehouse X is - [20 22 19]


## Tasks
16. Find the row/column positions in `warehouse_Y` where the value is above `95`. Build a new version of `warehouse_Y` where every value above `95` is replaced with `100`, and everything else stays the same.

17. Given `daily_flags = np.array([0, 0, 5, 0, 3, 0, 8])`, print the positions of every entry that is not zero. Given `watch_codes = np.array([301, 999])`, check `product_codes` against it and print the actual values from `product_codes` that match.

18. Remove the value at position 0 from `stock`, in one line. Remove product row index 2 from `warehouse_X`. Remove month column index 1 from `warehouse_Y`. Print all three results.

19. Attach `[[45, 48, 50]]` onto `warehouse_X` without giving any extra dimension setting, and print the shape. Then attach it again properly as a new row, and print that shape. Do the same comparison for removing index 0 from `warehouse_X` — once with no dimension setting, once removing a full column — printing both shapes.

20. On `monthly_sales`, check which individual values are missing and print the True/False grid. Print only the actual missing values pulled out from the array. Print the total count of missing values in the whole array.

In [30]:
# 16
Rows,Columns = np.where(Warehouse_Y > 95)
print("Rows Index -",Rows)
print("Column Index -",Columns)

New_Version = np.where(Warehouse_Y > 95 , 100, Warehouse_Y)
print("The New Version of Warehouse Y is -",New_Version)

Rows Index - [2 2 2]
Column Index - [0 1 2]
The New Version of Warehouse Y is - [[ 90  95  92]
 [ 40  42  38]
 [100 100 100]
 [ 25  27  24]]


In [34]:
# 17
Daily_flags = np.array([0, 0, 5, 0, 3, 0, 8])
Watch_codes = np.array([301, 999])

Non_Zero = np.nonzero(Daily_flags)
print("Entry that is not zero in Daily Flags is -",Non_Zero)

Check = Product_Codes[np.isin(Product_Codes,Watch_codes)]
print("The Values after checking Product code agaist watch codes -",Check)

Entry that is not zero in Daily Flags is - (array([2, 4, 6]),)
The Values after checking Product code agaist watch codes - [301 301 301]


In [37]:
# 18
Delete_1 = np.delete(Stock,0)
print("Stock After Remove the value at position 0 from stock -",Delete_1)

Delete_2 = np.delete(Warehouse_X,2,axis=0)
print("Warehouse X after Remove product row index 2 -",Delete_2)

Delete_3 = np.delete(Warehouse_Y,1,axis=1)
print("Warehouse Y after Remove month column index 1 -",Delete_3)

Stock After Remove the value at position 0 from stock - [12 58  9]
Warehouse X after Remove product row index 2 - [[50 55 60]
 [30 28 32]
 [20 22 19]]
Warehouse Y after Remove month column index 1 - [[ 90  92]
 [ 40  38]
 [100  98]
 [ 25  24]]


In [39]:
# 19
New_Sales = np.array([[45, 48, 50]])

Adding_New_Sales_1 = np.append(Warehouse_X,New_Sales)
print("Attach New Sales onto warehouse_X without giving any extra dimension setting -",Adding_New_Sales_1)
print("Shape of Warehouse X after Adding new sales without giving any extra dimension setting -",Adding_New_Sales_1.shape)

Adding_New_Sales_2 = np.append(Warehouse_X,New_Sales,axis=0)
print("Attach New Sales onto warehouse_X properly as a new row -",Adding_New_Sales_2)
print("Shape of Warehouse X after Adding properly as a new row-",Adding_New_Sales_2.shape)

Delete_4 = np.delete(Warehouse_X,0)
print("Remove Index 0 value from warehouse_X with no dimension setting -",Delete_4)
print("Shape After Removing Index 0 value from Warehouse - X -",Delete_4.shape)

Delete_5 = np.delete(Warehouse_X,0,axis=1)
print("Remove Index 0 value from warehouse_X with Removing full Column -",Delete_5)
print("Shape After Removing Index 0 as a column from Warehouse - X -",Delete_5.shape)

Attach New Sales onto warehouse_X without giving any extra dimension setting - [50 55 60 30 28 32 70 75 68 20 22 19 45 48 50]
Shape of Warehouse X after Adding new sales without giving any extra dimension setting - (15,)
Attach New Sales onto warehouse_X properly as a new row - [[50 55 60]
 [30 28 32]
 [70 75 68]
 [20 22 19]
 [45 48 50]]
Shape of Warehouse X after Adding properly as a new row- (5, 3)
Remove Index 0 value from warehouse_X with no dimension setting - [55 60 30 28 32 70 75 68 20 22 19]
Shape After Removing Index 0 value from Warehouse - X - (11,)
Remove Index 0 value from warehouse_X with Removing full Column - [[55 60]
 [28 32]
 [75 68]
 [22 19]]
Shape After Removing Index 0 as a column from Warehouse - X - (4, 2)


In [40]:
# 20
Missing_Values = np.isnan(Monthly_sales)
print("Checking which individual values are missing from monthly sales -",Missing_Values)

Actual_missing_values = Monthly_sales[np.any(Monthly_sales)]
print("Printing actual missing values from monthly sales -",Actual_missing_values)

Total_Missing_Values = np.sum(np.isnan(Monthly_sales))
print("Total Missing Values in Monthly Sales -",Total_Missing_Values)

Checking which individual values are missing from monthly sales - [[False False  True False False False]
 [False  True False False False  True]
 [False False False  True False False]
 [False False False False  True False]]
Printing actual missing values from monthly sales - [[[220. 240.  nan 260. 210. 230.]
  [110.  nan 130. 125. 118.  nan]
  [340. 355. 360.  nan 348. 352.]
  [ 95.  88.  92.  90.  nan  85.]]]
Total Missing Values in Monthly Sales - 5


## Tasks
21. Check if `monthly_sales` has at least one missing value anywhere, print the result. Check if every single value in row index 1 of `monthly_sales` is missing, print the result. Find the exact row/column positions of every missing value in `monthly_sales`. Replace every missing value in a copy of `monthly_sales` with `0` and print it.

22. Calculate the average of each row in `monthly_sales` in a way that correctly skips missing values, and print it. Separately, calculate the overall minimum and maximum of `monthly_sales` while correctly skipping missing values.

23. Make a copy of `monthly_sales`. For that copy, work out the correct average of each row ignoring missing values, and then fill every missing value in that row with that row's average. Print the final cleaned array with no missing values left.

24. Make a copy of `warehouse_X`. Change the value in row 0, column 1 to `58`. Change every value in row 2 to `72` in one line. Change every value greater than `50` to `999` using a condition. Change row 0, columns 0 and 2 to `10` and `12` respectively, in one line.

25. Make another copy of `warehouse_Y`. Replace the entire second row with `[41, 43, 39]`. Replace the entire last column with `[30, 30, 30, 30]`. Then, in a fresh copy of `monthly_sales`, directly set every missing value to `999` using a condition-based update (not `np.where()`), and print the result.


In [42]:
# 21
Checking_missing_values_any = np.any(np.isnan(Monthly_sales))
print("Checking if monthly_sales has at least one missing value anywhere -",Checking_missing_values_any)

Checking_missing_values_all = np.all(np.isnan(Monthly_sales),axis=0)
print("Checking if monthly_sales every single value in row index 1 of monthly_sales is missing -",Checking_missing_values_all)

Rows,Columns = np.where(np.isnan(Monthly_sales))
print("Rows index of missing values -",Rows)
print("Column index of missing values -",Columns)

Checking if monthly_sales has at least one missing value anywhere - True
Checking if monthly_sales every single value in row index 1 of monthly_sales is missing - [False False False False False False]
Rows index of missing values - [0 1 1 2 3]
Column index of missing values - [2 1 5 3 4]


In [43]:
# 22
Row_Average = np.nanmean(Monthly_sales,axis=0)
print("The Average of Each Row is -",Row_Average)

Min_Monthly_Sales = np.nanmin(Monthly_sales)
print("The min monthly sales is -",Min_Monthly_Sales)

Max_Monthly_Sales = np.nanmax(Monthly_sales)
print("The Max Monthly sales is -",Max_Monthly_Sales)

The Average of Each Row is - [191.25       227.66666667 194.         158.33333333 225.33333333
 222.33333333]
The min monthly sales is - 85.0
The Max Monthly sales is - 360.0


In [45]:
# 23
np.set_printoptions(linewidth=200)
Insert_Row_Average = np.where(np.isnan(Monthly_sales),Row_Average,Monthly_sales)
print("Result after fill every missing value in that row with that row's average -",Insert_Row_Average)

Result after fill every missing value in that row with that row's average - [[220.         240.         194.         260.         210.         230.        ]
 [110.         227.66666667 130.         125.         118.         222.33333333]
 [340.         355.         360.         158.33333333 348.         352.        ]
 [ 95.          88.          92.          90.         225.33333333  85.        ]]


In [51]:
# 24
Warehouse_X_copy = Warehouse_X.copy()

Warehouse_X_copy[0,1] = 58
print("After Updating Warehouse X value  in row 0, column 1 to 58 -",Warehouse_X_copy)

Warehouse_X_copy[1] = 58
print("After Updating Warehouse X value of whole row 2 to 58 -",Warehouse_X_copy)

Warehouse_X_copy[Warehouse_X_copy>50] = 99
print("After Updating Warehouse X value where value that is greater than 50 to 99 -",Warehouse_X_copy)

Warehouse_X_copy[0,[0,2]] = [10,12]
print("After Updating Warehouse X value where  row 0, columns 0 and 2 to 10 and 12 -",Warehouse_X_copy)

After Updating Warehouse X value  in row 0, column 1 to 58 - [[50 58 60]
 [30 28 32]
 [70 75 68]
 [20 22 19]]
After Updating Warehouse X value of whole row 2 to 58 - [[50 58 60]
 [58 58 58]
 [70 75 68]
 [20 22 19]]
After Updating Warehouse X value where value that is greater than 50 to 99 - [[50 99 99]
 [99 99 99]
 [99 99 99]
 [20 22 19]]
After Updating Warehouse X value where  row 0, columns 0 and 2 to 10 and 12 - [[10 99 12]
 [99 99 99]
 [99 99 99]
 [20 22 19]]


In [55]:
# 25
Warehouse_Y_copy = Warehouse_Y.copy()
Monthly_sales_Copy = Monthly_sales.copy()

Warehouse_Y_copy[2] = [41, 43, 39]
print("After Updating whole 2 row in Warehouse Y with 41,43,39 -",Warehouse_Y_copy)

Warehouse_Y_copy[:,-1] = [30,30,30,30]
print("After Updating last column with value 30 -",Warehouse_Y_copy)

Monthly_sales_Copy[np.isnan(Monthly_sales_Copy)] = 999
print("After Updating missing values of Monthly Sales with 999 -",Monthly_sales_Copy)

After Updating whole 2 row in Warehouse Y with 41,43,39 - [[90 95 92]
 [40 42 38]
 [41 43 39]
 [25 27 24]]
After Updating last column with value 30 - [[90 95 30]
 [40 42 30]
 [41 43 30]
 [25 27 30]]
After Updating missing values of Monthly Sales with 999 - [[220. 240. 999. 260. 210. 230.]
 [110. 999. 130. 125. 118. 999.]
 [340. 355. 360. 999. 348. 352.]
 [ 95.  88.  92.  90. 999.  85.]]
