In [2]:
import numpy as np

# Sample Data
Daily units sold for 5 products, over 3 days (each row = one day, each column = one product):

In [7]:
Sales_list = [
    [12, 45, 8, 22, 5],
    [15, 40, 10, 18, 7],
    [9, 50, 6, 25, 4]
]

## Part 1 — Array Creation
### Tasks
1. **`np.array()`** — Convert `sales_list` into a NumPy array called `sales`.
2. **`np.zeros()`** — NovaMart is opening a new store with the same 5 products but no sales yet. Create a 1D array of 5 zeros representing its first day.
3. **`np.ones()`** — Create a 3×5 array of all 1s to use as a "minimum stock guarantee" array (every product, every day, at least 1 unit reserved).
4. **`np.full()`** — Create a 3×5 array where every value is `20`, representing a flat reorder threshold for every product on every day.
5. **`np.arange()`** — Create an array of product IDs from 101 to 105 (5 products) using a start and stop value.
6. **`np.eye()`** — Create a 5×5 identity matrix. (Your lead wants this to later mark "exactly one product on discount per day" — explain in one line why an identity matrix's shape fits that use case.)

In [54]:
# 1
Sales = np.array(Sales_list)
print("Sales Data -",Sales)

Sales Data - [[12 45  8 22  5]
 [15 40 10 18  7]
 [ 9 50  6 25  4]]


In [55]:
# 2
Sales_New = np.zeros(5 , dtype = int)
print("The 1d Array 0f zeros -",Sales_New)

The 1d Array 0f zeros - [0 0 0 0 0]


In [56]:
# 3
Sales_min_stock_gurantee = np.ones((3,5) , dtype = int)
print(Sales_min_stock_gurantee)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
# 4
Sales_Thresold = np.full((3,5) ,20 ,dtype = int)
print(Sales_Thresold)

[[20 20 20 20 20]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [12]:
# 5
Product_Ids = np.arange(101,106,dtype = int)
print(Product_Ids)

[101 102 103 104 105]


In [13]:
# 6
Identity_Matrix = np.eye((5,5),dtype = int)
print(Identity_Matrix)

TypeError: 'tuple' object cannot be interpreted as an integer

## Part 2 — Array Types & Attributes
Using the `sales` array from Task 1:

7. **`ndim`** — Confirm the dimension count using the attribute.
8. **`shape`** — Print the shape.
9. **`size`** — Print the total number of elements. Confirm it equals rows × columns.
10. **`dtype`** — Print the data type NumPy chose automatically.
11. **`itemsize`** — Print how many bytes one element takes up.

In [14]:
# 7
Dimensions = np.ndim(Sales)
print("Dimension -",Dimensions)

Dimension - 2


In [15]:
# 8
Shape = np.shape(Sales)
print("Shape -",Shape)

Shape - (3, 5)


In [16]:
# 9
Size = np.size(Sales)
print("Size -",Size)

Manula_Size = Shape[0]*Shape[1]
print("Manual Calculation of Size -",Manula_Size)

Size - 15
Manual Calculation of Size - 15


In [99]:
# 10
DataType = Sales.dtype
print(DataType)

int64


In [100]:
# 11
ItemSize = Sales.itemsize
print(ItemSize)

8


## Part 3 — Reshaping
12. **`reshape()`** — Reshape `sales` (3×5 = 15 elements) into a shape of `(5, 3)`. Confirm the total element count hasn't changed.
13. **`flatten()`** — Flatten `sales` into a single 1D array. How many elements does it have?
14. **`ravel()`** — Do the same using `ravel()`. Both `flatten()` and `ravel()` give a 1D array — after checking the docs/notes, state one practical difference between them (hint: does one create a copy and the other a view?).
15. **`transpose()`** — Transpose `sales` so that rows become columns. What was `(3, 5)` should now be `(5, 3)`
16. **`resize()`** — Take a copy of `sales` and resize it (in place) to shape `(2, 5)`. Since this shape only holds 10 elements out of the original 1 explain what happened to the missing data.

In [26]:
# 12
Reshape = np.reshape(Sales,shape = (5,3))
print(Reshape)

Reshape_Size = np.size(Reshape)
print("Reshape Size -",Reshape_Size)

[[12 45  8]
 [22  5 15]
 [40 10 18]
 [ 7  9 50]
 [ 6 25  4]]
Reshape Size - 15


In [31]:
# 13
Flatten = Sales.flatten()
print(Flatten)

Flatten_Size = np.size(Flatten)
print("Flatten_Size -",Reshape_Size)

[12 45  8 22  5 15 40 10 18  7  9 50  6 25  4]
Flatten_Size - 15


In [32]:
# 14
Ravel = Sales.ravel()
print(Ravel)

Ravel_Size = np.size(Ravel)
print("Ravel_Size -",Reshape_Size)

[12 45  8 22  5 15 40 10 18  7  9 50  6 25  4]
Ravel_Size - 15


In [33]:
# 15
Transpose = Sales.transpose()
print(Transpose)

[[12 15  9]
 [45 40 50]
 [ 8 10  6]
 [22 18 25]
 [ 5  7  4]]


In [35]:
# 16
Resize = np.resize(Sales,(2,5))
print(Resize)

print("Last 5 Elements is Removed")

[[12 45  8 22  5]
 [15 40 10 18  7]]
Last 5 Elements is Removed


# Sample Data

In [38]:
Prices = np.array([250.75, 89.30, 610.00, 45.60, 320.15])
Stock  = np.array([12, 45, 8, 22, 5])

## Part 4 — Mathematical Functions
17. **`np.multiply()`** — Calculate the total inventory value per product (price × stock).
18. **`np.sum()`** — Find the total inventory value across all 5 products.
19. **`np.add()` / `np.subtract()`** — A new shipment adds `[5, 10, 2, 8, 1]` units to `stock`. Compute the new stock levels. Then, 3 units of each product were found damaged and removed — subtract `3` from every product's stock using a single line (broadcasting).
20. **`np.mean()` / `np.median()` / `np.std()` / `np.var()`** — For the `prices` array, calculate all four. In one line, explain what the std tells you about how varied NovaMart's pricing is.
21. **`np.min()` / `np.max()`** — Find the cheapest and most expensive product prices.
22. **`np.round()` / `np.floor()` / `np.ceil()`** — NovaMart wants prices displayed three ways: rounded to the nearest ₹1, always rounded down, and always rounded up. Apply all three to `prices`.
23. **`np.sqrt()` / `np.power()`** — A discount formula NovaMart uses is `sqrt(price) * 2` for calculating loyalty points. Apply it to `prices`. Separately, use `np.power()` to calculate the square of the `stock` array (used in a variance calculation elsewhere).
24. **`np.abs()`** — A stock adjustment log shows changes as `[-3, 5, -2, 0, -1]` (negative = removed, positive = added). Use `abs()` to get the magnitude of change per product, ignoring direction.
25. **`np.prod()`** — Compute the product of all values in `stock`

In [39]:
# 17
Multiply = np.multiply(Prices,Stock)
print("The total inventory value per product is -",Multiply)

The total inventory value per product is - [3009.   4018.5  4880.   1003.2  1600.75]


In [42]:
# 18
Sum = np.sum(Multiply)
print("The total inventory value across all 5 products -",Sum)

The total inventory value across all 5 products - 14511.45


In [47]:
# 19
Array = np.array([5,10,2,8,1])
print("The New Shipment -",Array)

Add = np.add(Stock,Array)
print("The New Stock Level is -",Add)

Subtract = np.subtract(Stock,3)
print("The New stock after removing damaged Product -",Subtract)

The New Shipment - [ 5 10  2  8  1]
The New Stock Level is - [17 55 10 30  6]
The New stock after removing damaged Product - [ 9 42  5 19  2]


In [52]:
# 20
Mean = np.mean(Prices)
print("The Avg Price is -",Mean)

Median = np.median(Prices)
print("The Middle Price is -",Median)

Standard_Deviation = np.std(Prices)
print("The Standard Deviation is -",Standard_Deviation)

Variance = np.var(Prices)
print("The Variance is -",Variance)

## The product prices have considerable variation. Some products are inexpensive, while others are much more expensive.

The Avg Price is - 263.15999999999997
The Middle Price is - 250.75
The Standard Deviation is - 200.62876513600935
The Variance is - 40251.901399999995


In [53]:
# 21
Min = np.min(Prices)
print("The Min Price is -",Min)

Max = np.max(Prices)
print("The Max Price is -",Max)

The Min Price is - 45.6
The Max Price is - 610.0


In [59]:
# 22
Round = np.round(Prices)
print("Prices rounded to the nearest ₹1 -",Round)

Floor = np.floor(Prices)
print("Prices rounded down -",Floor)

Ceil = np.ceil(Prices)
print("Prices rounded up -",Ceil)

Prices rounded to the nearest ₹1 - [251.  89. 610.  46. 320.]
Prices rounded down - [250.  89. 610.  45. 320.]
Prices rounded up - [251.  90. 610.  46. 321.]


In [64]:
# 23
Square_Root = np.sqrt(Prices)*2
print("Loyalty Points is -",Square_Root)

Power = np.power(Stock,2)
print("The square of the stock array -",Power)

Loyalty Points is - [31.67017524 18.89973545 49.39635614 13.50555441 35.78547191]
The square of the stock array - [ 144 2025   64  484   25]


In [66]:
# 24
Array_2 = np.array([-3, 5, -2, 0, -1])
print("A stock adjustment log shows changes as -",Array_2)

Absolute = np.abs(Array_2)
print("The magnitude of change per product, ignoring direction -",Absolute)

A stock adjustment log shows changes as - [-3  5 -2  0 -1]
The magnitude of change per product, ignoring direction - [3 5 2 0 1]


In [67]:
# 25
Prod = np.prod(Stock)
print("The Prod of Stock -",Prod)

The Prod of Stock - 475200


## Part 5 — Indexing
Using the original `sales` array (3 days × 5 products):

26. Access the units sold for **Product 3 (index 2) on Day 2 (index 1)** using 2D indexing.
27. Access the **entire Day 1 row** (all products) using row-only indexing.
28. Use **negative indexing** to get the sales value for the **last product on the last day** without knowing the array's exact size.
29. Build a small 3D array of shape `(2, 3, 5)` representing two warehouses, each with the same 3-day, 5-product layout as `sales` (you can duplicate `sales_list` twice into a new array). Then index into it to retrieve **Warehouse 2, Day 3, Product 1**'s value.

In [70]:
print(Sales)

[[12 45  8 22  5]
 [15 40 10 18  7]
 [ 9 50  6 25  4]]


In [75]:
# 26
Indexing_1 = Sales[1,2]
print("The units sold for Product 3 on Day 2 -",Indexing_1)

The units sold for Product 3 on Day 2 - 10


In [78]:
# 27
Indexing_2 = Sales[0]
print("The entire Day 1 row is -",Indexing_2)

The entire Day 1 row is - [12 45  8 22  5]


In [81]:
# 28
Indexing_3 = Sales[-1,-1]
print("The sales value for the last product on the last day -",Indexing_3)

The sales value for the last product on the last day - 4


## Part 6 — Slicing
30. Slice `sales` to get **only Day 1 and Day 2** (rows 0 and 1), all products.
31. Slice `sales` to get **only the last 3 products** (columns) for all days.
32. Slice `sales` using a **step of 2** to get every other product (columns 0, 2, 4) across all days.
33. Slice `prices` to get products from index 1 up to (but not including) index 4.


In [85]:
print(Sales)

[[12 45  8 22  5]
 [15 40 10 18  7]
 [ 9 50  6 25  4]]


In [87]:
# 30
Slicing_1 = Sales[0:2]
print("Day 1 and Day Sales of all Products -",Slicing_1)

Day 1 and Day Sales of all Products - [[12 45  8 22  5]
 [15 40 10 18  7]]


In [93]:
# 31
Slicing_2 = Sales[::,2:]
print("The last 3 products sales for all Days -",Slicing_2)

The last 3 products sales for all Days - [[ 8 22  5]
 [10 18  7]
 [ 6 25  4]]


In [95]:
# 32
Slicing_3 = Sales[::,0::2]
print("The every other product across all days -",Slicing_3)

The every other product across all days - [[12  8  5]
 [15 10  7]
 [ 9  6  4]]


In [97]:
# 33
Slicing_4 = Prices[1:4]
print("The products from index 1 up to (but not including) index 4 -",Slicing_4)

The products from index 1 up to (but not including) index 4 - [ 89.3 610.   45.6]
